skip-check:
  - CKV2_AWS_5
  - CKV2_AWS_37
  - CKV2_AWS_41
  - CKV_AWS_145
  - CKV_AWS_19
  - CKV_AWS_18
  - CKV_AWS_144
  - CKV_AWS_145
  - CKV_AWS_21
  - CKV2_AWS_6
  - CKV2_AWS_41
  - CKV2_AWS_37
  - CKV2_AWS_28
  - CKV2_AWS_20
  - CKV_AWS_8
  - CKV_AWS_126
  - CKV_AWS_79
  - CKV_AWS_135
  - CKV_AWS_46
