alter table yjb_case_reporting.mvw_yp_assessment_alerts_flags owner to yjb_schedular;	
alter table yjb_case_reporting.mvw_yp_assessment_stage_details owner to yjb_schedular;	
alter table yjb_case_reporting.mvw_yp_asset_plus owner to yjb_schedular;	
alter table yjb_case_reporting.mvw_yp_asset_plus_ete_details owner to yjb_schedular;	
alter table yjb_case_reporting.mvw_yp_asset_plus_fad owner to yjb_schedular;	
alter table yjb_case_reporting.mvw_yp_asset_plus_ffd owner to yjb_schedular;	
alter table yjb_case_reporting.mvw_yp_asset_plus_risk_of_harm owner to yjb_schedular;	
alter table yjb_case_reporting.mvw_yp_asset_plus_saw owner to yjb_schedular;	
alter table yjb_case_reporting.mvw_yp_asset_plus_substance_misuse owner to yjb_schedular;	
alter table yjb_case_reporting.mvw_yp_care_status owner to yjb_schedular;	
alter table yjb_case_reporting.mvw_yp_ete_status owner to yjb_schedular;	
alter table yjb_case_reporting.mvw_yp_hearing_sentence_proposal owner to yjb_schedular;	
alter table yjb_case_reporting.mvw_yp_intervention_programme owner to yjb_schedular;	
alter table yjb_case_reporting.mvw_yp_link_hearing_intervention_programme owner to yjb_schedular;	
alter table yjb_case_reporting.mvw_yp_link_intervention_programme_asset owner to yjb_schedular;	
alter table yjb_case_reporting.mvw_yp_link_intervention_programme_parenting_intervention owner to yjb_schedular;	
alter table yjb_case_reporting.mvw_yp_link_offence_intervention_programme owner to yjb_schedular;	
alter table yjb_case_reporting.mvw_yp_link_offence_victim_intervention owner to yjb_schedular;	
alter table yjb_case_reporting.mvw_yp_parenting_intervention owner to yjb_schedular;	
alter table yjb_case_reporting.mvw_yp_residence owner to yjb_schedular;	
alter table yjb_case_reporting.mvw_yp_transfer owner to yjb_schedular;	
alter table yjb_case_reporting.mvw_yp_victim_intervention owner to yjb_schedular;	

grant select on yjb_case_reporting.mvw_yp_assessment_alerts_flags to group yjb_data_science;	grant select on yjb_case_reporting.mvw_yp_assessment_alerts_flags to group yjb_ianda_team;	grant select on yjb_case_reporting.mvw_yp_assessment_alerts_flags to "IAMR:redshift-serverless-yjb-reporting-moj_ap";	
grant select on yjb_case_reporting.mvw_yp_assessment_stage_details to group yjb_data_science;	grant select on yjb_case_reporting.mvw_yp_assessment_stage_details to group yjb_ianda_team;	grant select on yjb_case_reporting.mvw_yp_assessment_stage_details to "IAMR:redshift-serverless-yjb-reporting-moj_ap";	
grant select on yjb_case_reporting.mvw_yp_asset_plus to group yjb_data_science;	grant select on yjb_case_reporting.mvw_yp_asset_plus to group yjb_ianda_team;	grant select on yjb_case_reporting.mvw_yp_asset_plus to "IAMR:redshift-serverless-yjb-reporting-moj_ap";	
grant select on yjb_case_reporting.mvw_yp_asset_plus_ete_details to group yjb_data_science;	grant select on yjb_case_reporting.mvw_yp_asset_plus_ete_details to group yjb_ianda_team;	grant select on yjb_case_reporting.mvw_yp_asset_plus_ete_details to "IAMR:redshift-serverless-yjb-reporting-moj_ap";	
grant select on yjb_case_reporting.mvw_yp_asset_plus_fad to group yjb_data_science;	grant select on yjb_case_reporting.mvw_yp_asset_plus_fad to group yjb_ianda_team;	grant select on yjb_case_reporting.mvw_yp_asset_plus_fad to "IAMR:redshift-serverless-yjb-reporting-moj_ap";	
grant select on yjb_case_reporting.mvw_yp_asset_plus_ffd to group yjb_data_science;	grant select on yjb_case_reporting.mvw_yp_asset_plus_ffd to group yjb_ianda_team;	grant select on yjb_case_reporting.mvw_yp_asset_plus_ffd to "IAMR:redshift-serverless-yjb-reporting-moj_ap";	
grant select on yjb_case_reporting.mvw_yp_asset_plus_risk_of_harm to group yjb_data_science;	grant select on yjb_case_reporting.mvw_yp_asset_plus_risk_of_harm to group yjb_ianda_team;	grant select on yjb_case_reporting.mvw_yp_asset_plus_risk_of_harm to "IAMR:redshift-serverless-yjb-reporting-moj_ap";	
grant select on yjb_case_reporting.mvw_yp_asset_plus_saw to group yjb_data_science;	grant select on yjb_case_reporting.mvw_yp_asset_plus_saw to group yjb_ianda_team;	grant select on yjb_case_reporting.mvw_yp_asset_plus_saw to "IAMR:redshift-serverless-yjb-reporting-moj_ap";	
grant select on yjb_case_reporting.mvw_yp_asset_plus_substance_misuse to group yjb_data_science;	grant select on yjb_case_reporting.mvw_yp_asset_plus_substance_misuse to group yjb_ianda_team;	grant select on yjb_case_reporting.mvw_yp_asset_plus_substance_misuse to "IAMR:redshift-serverless-yjb-reporting-moj_ap";	
grant select on yjb_case_reporting.mvw_yp_care_status to group yjb_data_science;	grant select on yjb_case_reporting.mvw_yp_care_status to group yjb_ianda_team;	grant select on yjb_case_reporting.mvw_yp_care_status to "IAMR:redshift-serverless-yjb-reporting-moj_ap";	
grant select on yjb_case_reporting.mvw_yp_ete_status to group yjb_data_science;	grant select on yjb_case_reporting.mvw_yp_ete_status to group yjb_ianda_team;	grant select on yjb_case_reporting.mvw_yp_ete_status to "IAMR:redshift-serverless-yjb-reporting-moj_ap";	
grant select on yjb_case_reporting.mvw_yp_hearing_sentence_proposal to group yjb_data_science;	grant select on yjb_case_reporting.mvw_yp_hearing_sentence_proposal to group yjb_ianda_team;	grant select on yjb_case_reporting.mvw_yp_hearing_sentence_proposal to "IAMR:redshift-serverless-yjb-reporting-moj_ap";	
grant select on yjb_case_reporting.mvw_yp_intervention_programme to group yjb_data_science;	grant select on yjb_case_reporting.mvw_yp_intervention_programme to group yjb_ianda_team;	grant select on yjb_case_reporting.mvw_yp_intervention_programme to "IAMR:redshift-serverless-yjb-reporting-moj_ap";	
grant select on yjb_case_reporting.mvw_yp_link_hearing_intervention_programme to group yjb_data_science;	grant select on yjb_case_reporting.mvw_yp_link_hearing_intervention_programme to group yjb_ianda_team;	grant select on yjb_case_reporting.mvw_yp_link_hearing_intervention_programme to "IAMR:redshift-serverless-yjb-reporting-moj_ap";	
grant select on yjb_case_reporting.mvw_yp_link_intervention_programme_asset to group yjb_data_science;	grant select on yjb_case_reporting.mvw_yp_link_intervention_programme_asset to group yjb_ianda_team;	grant select on yjb_case_reporting.mvw_yp_link_intervention_programme_asset to "IAMR:redshift-serverless-yjb-reporting-moj_ap";	
grant select on yjb_case_reporting.mvw_yp_link_intervention_programme_parenting_intervention to group yjb_data_science;	grant select on yjb_case_reporting.mvw_yp_link_intervention_programme_parenting_intervention to group yjb_ianda_team;	grant select on yjb_case_reporting.mvw_yp_link_intervention_programme_parenting_intervention to "IAMR:redshift-serverless-yjb-reporting-moj_ap";	
grant select on yjb_case_reporting.mvw_yp_link_offence_intervention_programme to group yjb_data_science;	grant select on yjb_case_reporting.mvw_yp_link_offence_intervention_programme to group yjb_ianda_team;	grant select on yjb_case_reporting.mvw_yp_link_offence_intervention_programme to "IAMR:redshift-serverless-yjb-reporting-moj_ap";	
grant select on yjb_case_reporting.mvw_yp_link_offence_victim_intervention to group yjb_data_science;	grant select on yjb_case_reporting.mvw_yp_link_offence_victim_intervention to group yjb_ianda_team;	grant select on yjb_case_reporting.mvw_yp_link_offence_victim_intervention to "IAMR:redshift-serverless-yjb-reporting-moj_ap";	
grant select on yjb_case_reporting.mvw_yp_parenting_intervention to group yjb_data_science;	grant select on yjb_case_reporting.mvw_yp_parenting_intervention to group yjb_ianda_team;	grant select on yjb_case_reporting.mvw_yp_parenting_intervention to "IAMR:redshift-serverless-yjb-reporting-moj_ap";	
grant select on yjb_case_reporting.mvw_yp_residence to group yjb_data_science;	grant select on yjb_case_reporting.mvw_yp_residence to group yjb_ianda_team;	grant select on yjb_case_reporting.mvw_yp_residence to "IAMR:redshift-serverless-yjb-reporting-moj_ap";	
grant select on yjb_case_reporting.mvw_yp_transfer to group yjb_data_science;	grant select on yjb_case_reporting.mvw_yp_transfer to group yjb_ianda_team;	grant select on yjb_case_reporting.mvw_yp_transfer to "IAMR:redshift-serverless-yjb-reporting-moj_ap";	
grant select on yjb_case_reporting.mvw_yp_victim_intervention to group yjb_data_science;	grant select on yjb_case_reporting.mvw_yp_victim_intervention to group yjb_ianda_team;	grant select on yjb_case_reporting.mvw_yp_victim_intervention to "IAMR:redshift-serverless-yjb-reporting-moj_ap";	
