ALTER TABLE yjb_ianda_team.all_2022 OWNER TO "IAMR:admin";	
ALTER TABLE yjb_ianda_team.custodies_since_2014 OWNER TO "oriana_delgado";	
ALTER TABLE yjb_ianda_team.data_quality_bs_costs OWNER TO "oriana_delgado";	
ALTER TABLE yjb_ianda_team.data_quality_bs_gender_ethnicity OWNER TO "oriana_delgado";	
ALTER TABLE yjb_ianda_team.data_quality_bs_staff_by_contract OWNER TO "oriana_delgado";	
ALTER TABLE yjb_ianda_team.data_quality_general OWNER TO "oriana_delgado";	
ALTER TABLE yjb_ianda_team.data_quality_kpi10 OWNER TO "IAMR:admin";	
ALTER TABLE yjb_ianda_team.data_request_ecm_2023 OWNER TO "IAMR:admin";	
ALTER TABLE yjb_ianda_team.filter_data_request_ecm_2023 OWNER TO "IAMR:admin";	
ALTER TABLE yjb_ianda_team.fte_redshift OWNER TO "john_beavis";	
ALTER TABLE yjb_ianda_team.kpi1 OWNER TO "adela_illiescu";	
ALTER TABLE yjb_ianda_team.mvw_return_part_deleted_yps OWNER TO "sam_mohammed";	
ALTER TABLE yjb_ianda_team.mvw_return_part_deleted_yps_ak OWNER TO "alexander_key";	
ALTER TABLE yjb_ianda_team.residence_distinct OWNER TO "adela_illiescu";	
ALTER TABLE yjb_ianda_team.sexual_offences_since_2016 OWNER TO "oriana_delgado";	
ALTER TABLE yjb_ianda_team.sexual_offences_since_2016_all_offences OWNER TO "john_beavis";	
ALTER TABLE yjb_ianda_team.sv_2020_2024 OWNER TO "oriana_delgado";	
ALTER TABLE yjb_ianda_team.yjs_family_unpivoted OWNER TO "oriana_delgado";	
ALTER TABLE yjb_ianda_team.yjs_family_unpivoted_v2 OWNER TO "oriana_delgado";	
ALTER TABLE yjb_ianda_team.yro_moj_jb OWNER TO "john_beavis";	

GRANT ALL on yjb_ianda_team.all_2022 TO group yjb_ianda_team;	
--GRANT ALL on yjb_ianda_team.custodies_since_2014 TO group yjb_ianda_team;	
GRANT ALL on yjb_ianda_team.data_quality_bs_costs TO group yjb_ianda_team;	
GRANT ALL on yjb_ianda_team.data_quality_bs_gender_ethnicity TO group yjb_ianda_team;	
GRANT ALL on yjb_ianda_team.data_quality_bs_staff_by_contract TO group yjb_ianda_team;	
GRANT ALL on yjb_ianda_team.data_quality_general TO group yjb_ianda_team;	
GRANT ALL on yjb_ianda_team.data_quality_kpi10 TO group yjb_ianda_team;	
GRANT ALL on yjb_ianda_team.data_request_ecm_2023 TO group yjb_ianda_team;	
GRANT ALL on yjb_ianda_team.filter_data_request_ecm_2023 TO group yjb_ianda_team;	
GRANT ALL on yjb_ianda_team.fte_redshift TO group yjb_ianda_team;	
--GRANT ALL on yjb_ianda_team.kpi1 TO group yjb_ianda_team;	
--GRANT ALL on yjb_ianda_team.mvw_return_part_deleted_yps TO group yjb_ianda_team;	
--GRANT ALL on yjb_ianda_team.mvw_return_part_deleted_yps_ak TO group yjb_ianda_team;	
--GRANT ALL on yjb_ianda_team.residence_distinct TO group yjb_ianda_team;	
GRANT ALL on yjb_ianda_team.sexual_offences_since_2016 TO group yjb_ianda_team;	
--GRANT ALL on yjb_ianda_team.sexual_offences_since_2016_all_offences TO group yjb_ianda_team;	
GRANT ALL on yjb_ianda_team.sv_2020_2024 TO group yjb_ianda_team;	
--GRANT ALL on yjb_ianda_team.yjs_family_unpivoted TO group yjb_ianda_team;	
--GRANT ALL on yjb_ianda_team.yjs_family_unpivoted_v2 TO group yjb_ianda_team;	
--GRANT ALL on yjb_ianda_team.yro_moj_jb TO group yjb_ianda_team;	

GRANT ALL on yjb_ianda_team.all_2022 TO "IAMR:redshift-serverless-yjb-reporting-moj_ap";	
--GRANT ALL on yjb_ianda_team.custodies_since_2014 TO "IAMR:redshift-serverless-yjb-reporting-moj_ap";	
GRANT ALL on yjb_ianda_team.data_quality_bs_costs TO "IAMR:redshift-serverless-yjb-reporting-moj_ap";	
GRANT ALL on yjb_ianda_team.data_quality_bs_gender_ethnicity TO "IAMR:redshift-serverless-yjb-reporting-moj_ap";	
GRANT ALL on yjb_ianda_team.data_quality_bs_staff_by_contract TO "IAMR:redshift-serverless-yjb-reporting-moj_ap";	
--GRANT ALL on yjb_ianda_team.data_quality_general TO "IAMR:redshift-serverless-yjb-reporting-moj_ap";	
GRANT ALL on yjb_ianda_team.data_quality_kpi10 TO "IAMR:redshift-serverless-yjb-reporting-moj_ap";	
GRANT ALL on yjb_ianda_team.data_request_ecm_2023 TO "IAMR:redshift-serverless-yjb-reporting-moj_ap";	
GRANT ALL on yjb_ianda_team.filter_data_request_ecm_2023 TO "IAMR:redshift-serverless-yjb-reporting-moj_ap";	
--GRANT ALL on yjb_ianda_team.fte_redshift TO "IAMR:redshift-serverless-yjb-reporting-moj_ap";	
GRANT ALL on yjb_ianda_team.kpi1 TO "IAMR:redshift-serverless-yjb-reporting-moj_ap";	
GRANT ALL on yjb_ianda_team.mvw_return_part_deleted_yps TO "IAMR:redshift-serverless-yjb-reporting-moj_ap";	
GRANT ALL on yjb_ianda_team.mvw_return_part_deleted_yps_ak TO "IAMR:redshift-serverless-yjb-reporting-moj_ap";	
GRANT ALL on yjb_ianda_team.residence_distinct TO "IAMR:redshift-serverless-yjb-reporting-moj_ap";	
--GRANT ALL on yjb_ianda_team.sexual_offences_since_2016 TO "IAMR:redshift-serverless-yjb-reporting-moj_ap";	
--GRANT ALL on yjb_ianda_team.sexual_offences_since_2016_all_offences TO "IAMR:redshift-serverless-yjb-reporting-moj_ap";	
--GRANT ALL on yjb_ianda_team.sv_2020_2024 TO "IAMR:redshift-serverless-yjb-reporting-moj_ap";	
GRANT ALL on yjb_ianda_team.yjs_family_unpivoted TO "IAMR:redshift-serverless-yjb-reporting-moj_ap";	
GRANT ALL on yjb_ianda_team.yjs_family_unpivoted_v2 TO "IAMR:redshift-serverless-yjb-reporting-moj_ap";	
--GRANT ALL on yjb_ianda_team.yro_moj_jb TO "IAMR:redshift-serverless-yjb-reporting-moj_ap";	

