SSOConfig:
  Default:
    StartUrl: https://moj.awsapps.com/start
    SSORegion: eu-west-2
DefaultRegion: eu-west-2
ConsoleDuration: 720
CacheRefresh: 168
UrlAction: print
LogLevel: error
HistoryLimit: 10
HistoryMinutes: 1440
ProfileFormat: "{{ FirstItem .AccountName (.AccountAlias | nospace) }}:{{ .RoleName }}"
FullTextSearch: true
