---
schemaVersion: "2.2"
description: Ensure Cloudwatch agent is installed and configured
parameters:
  optionalConfigurationLocation:
    description: name of ssm parameter that contains the CW Agent config
    type: String
    default: "cloud-watch-config-windows"
mainSteps:
  - name: installCWAgent
    action: aws:runDocument
    precondition:
      StringEquals:
        - platformType
        - Windows
    inputs:
      documentType: SSMDocument
      documentPath: AWS-ConfigureAWSPackage
      documentParameters:
        action: Install
        name: AmazonCloudWatchAgent
  - name: configureCWAgent
    action: aws:runDocument
    precondition:
      StringEquals:
        - platformType
        - Windows
    inputs:
      documentType: SSMDocument
      documentPath: AmazonCloudWatch-ManageAgent
      documentParameters:
        action: configure
        mode: ec2
        optionalConfigurationSource: ssm
        optionalConfigurationLocation: "{{ optionalConfigurationLocation }}"
        optionalRestart: "yes"
