---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production-http01
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ .Values.acme.email }}
    privateKeySecretRef:
      name: letsencrypt-production-http01
    solvers:
      - http01:
          ingress:
            ingressClassName: {{ .Values.httpIssuer.ingressClassName }}
