---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ .Values.acme.email }}
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - selector: {}
        dns01:
          cnameStrategy: Follow
          route53:
            region: {{ .Values.dnsIssuer.aws.region }}
