locals {
  db_userdata = <<-EOF
#!/bin/bash

# Disable requiretty
sed -i 's/^\(Defaults\s*requiretty\)/#\1/' /etc/sudoers

# Redirect all output to a log file and enable debugging
exec > /var/log/userdata.log 2>&1
set -x

#### USERDATA ######

#### install missing packages
echo "---install missing package "
sudo yum -y install libXp.i386
sudo yum -y install sshpass

# Hostname change
hostname edw
echo "HOSTNAME=${local.application_name}" >> /etc/sysconfig/network
sed -i '/aws/d' /etc/sysconfig/network
/etc/init.d/network restart

# Updating resolv.conf file and making immutable
echo "; generated by /sbin/dhclient-script
search ${data.aws_route53_zone.external.name} eu-west-2.compute.internal
nameserver ${local.dns_resolver_ip}" > /etc/resolv.conf
chattr +i /etc/resolv.conf

#### adjust the NTP (Network Time Protocol) settings to use the AWS time sync service as the time source
echo "---configure aws timesync (external ntp source)"

# Install chrony if not installed
if ! yum list installed chrony &>/dev/null; then
  sudo yum install -y chrony
fi

# Check if the chrony.conf file exists and is properly configured
if ! grep -q "server 169.254.169.123" /etc/chrony.conf; then
  sudo bash -c 'cat << EOC9 > /etc/chrony.conf
server 169.254.169.123 prefer iburst minpoll 4 maxpoll 4
# Record the rate at which the system clock gains/losses time.
driftfile /var/lib/chrony/drift
# Enable kernel RTC synchronization.
rtcsync
# In first three updates step the system clock instead of slew
# if the adjustment is larger than 1.0 seconds.
makestep 1.0 3
logdir /var/log/chrony
# Select which information is logged
log measurements statistics tracking
EOC9'
fi

# Start chronyd service
sudo /etc/init.d/chronyd start

#### Install AWS cli
echo "---Installing AWS cli"
wget -O awscliv2.zip "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
unzip -o awscliv2.zip
sudo ./aws/install --bin-dir /usr/local/bin --install-dir /usr/local/aws-cli --update

# Configure variables
export ip4=$(/sbin/ip -o -4 addr list eth0 | awk '{print $4}' | cut -d/ -f1)
export LOGS="${local.application_data.accounts[local.environment].edw_AppName}-EC2"
export APPNAME="${local.application_data.accounts[local.environment].edw_AppName}"
export ENV="${local.application_data.accounts[local.environment].edw_environment}"
export REGION="${local.application_data.accounts[local.environment].edw_region}"
export EFS="${aws_efs_file_system.edw.id}"
export SECRET=`/usr/local/bin/aws --region ${local.application_data.accounts[local.environment].edw_region} secretsmanager get-secret-value --secret-id ${aws_secretsmanager_secret.db-master-password2.id} --query SecretString --output text`
export host="$ip4 $APPNAME-$ENV infraedw"
echo $host >>/etc/hosts
sed -i '/^10.221/d' /etc/hosts
sed -i '0,/infraedw/{/infraedw/d;}' /etc/hosts

mkdir -p /home/oracle/scripts

# Updating hostname file
sed -i '1s/.*/edw/' /etc/hostname

mkdir -p /home/oracle/scripts

# Disable firewall
sudo /etc/init.d/iptables stop
sudo /sbin/chkconfig iptables off


# Install mailx
sudo yum install -y mailx
sudo ln -s /bin/mail /bin/mailx

# Configure maat db cron job script:

# Create the maat_05365_ware_db_changes.sh script
cat << 'EOC22' > /home/oracle/scripts/maat_05365_ware_db_changes.sh
#!/bin/ksh

# fixed variables
chown -R oracle:dba /home/oracle/scripts

LOCATE=/home/oracle/scripts
ORACLE_SID=$1; export ORACLE_SID
ORACLE_HOME=/oracle/software/product/10.2.0; export ORACLE_HOME
PATH=$ORACLE_HOME/bin:$PATH; export PATH

cd $LOCATE

sqlplus -s /nolog <<eosql >rundatafix.log
conn warehouse/whouse_prod
@maat_05365_ware_db_changes.sql
exit
eosql

# mailx -s "MI Production (EDW005) datafix 3079 \`date\`" digital_dba@digital.justice.gov.uk < rundatafix.log
EOC22

# Create the maat_05365_ware_db_changes.sql script
cat << 'EOC23' > /home/oracle/scripts/maat_05365_ware_db_changes.sql
--------------------------------------------------------------------------------------------------------------------
--
-- Archive:    %ARCHIVE%
-- Revision:   %PR%
-- Date:       %DATE%
--
-- Purpose: Modify warehouse tables to set column default values
--
--
-- Dimensions History
-- ------------------
--
-- Ver  Date     Name                 Description
-- ---- -------- -------------------- ------------------------------------------------------------------------------
-- 1.0  27/11/14 H Khela             Initial Version
--
--
--------------------------------------------------------------------------------------------------------------------
SPOOL maat_05365_ware_db_changes.log

-- Set time on so you can see how long each part takes
SET TIME ON

-- Set echo on so that you can see which command it is executing (and the time)
SET ECHO ON

ALTER TABLE warehouse.maat_assessment_fact MODIFY (
time_eff_to_dim_id NUMBER DEFAULT NULL);

ALTER TABLE warehouse.maat_application_dim MODIFY (
time_eff_to_dim_id NUMBER DEFAULT NULL);

  -- 9710356 rows updated.

  UPDATE warehouse.maat_assessment_fact
  SET time_eff_to_dim_id = NULL
  WHERE time_eff_to_dim_id = -1;

  COMMIT;

  -- 4558089 rows updated

  UPDATE warehouse.maat_application_dim
  SET time_eff_to_dim_id = NULL
  WHERE time_eff_to_dim_id = -1;

COMMIT;

SPOOL OFF
EOC23

echo "Setting up AWS EBS backup"
INSTANCE_ID=$(curl http://169.254.169.254/latest/meta-data/instance-id)
cat <<EOC25 > /home/oracle/scripts/aws_ebs_backup.sh
#!/bin/bash
/usr/local/bin/aws ec2 create-snapshots \
--instance-specification InstanceId=$INSTANCE_ID \
--description "AWS crash-consistent snapshots of EDW database volumes, automatically created snapshot from oracle_cron inside EC2" \
--copy-tags-from-source volume
EOC25

# Set up log files
echo "---creating /etc/awslogs/awscli.conf"
mkdir -p /etc/awslogs
cat > /etc/awslogs/awscli.conf <<-EOC1
[plugins]
cwlogs = cwlogs
[default]
region = $REGION
EOC1

echo "---creating /tmp/cwlogs/logstreams.conf"
mkdir -p /tmp/cwlogs

cat > /tmp/cwlogs/logstreams.conf <<-EOC2
[general]
state_file = /var/awslogs/agent-state

[cfn-init]
file = /var/log/cfn-init.log
log_group_name = $APPNAME-CfnInit
log_stream_name = {instance_id}

[oracle_alert_log_errors]
file = /oracle/software/product/10.2.0/admin/$APPNAME/bdump/alert_$APPNAME.log
log_group_name = $APPNAME-OracleAlerts
log_stream_name = {instance_id}

[rman_backup_log_errors]
file = /home/oracle/backup_logs/*_RMAN_disk_*.log
log_group_name = $APPNAME-RMan
log_stream_name = {instance_id}

[rman_arch_backup_log_errors]
file = /home/oracle/backup_logs/*_RMAN_disk_ARCH_*.log
log_group_name = $APPNAME-RManArch
log_stream_name = {instance_id}

[db_tablespace_space_alerts]
file = /home/oracle/scripts/logs/freespace_alert.log
log_group_name = $APPNAME-TBSFreespace
log_stream_name = {instance_id}

[db_PMON_status_alerts]
file = /home/oracle/scripts/logs/pmon_status_alert.log
log_group_name = $APPNAME-PMONstatus
log_stream_name = {instance_id}

[db_CDC_status_alerts]
file = /home/oracle/scripts/logs/cdc_check.log
log_group_name = $APPNAME-CDCstatus
log_stream_name = {instance_id}
EOC2

sudo chmod 755 /home/oracle/scripts/logs
sudo chmod 755 /etc/awslogs
sudo chmod 755 /tmp/cwlogs

##### METADATA #####

# #### Install_aws_logging
#  Very difficult to install aws logs due to outdated system so logstream does not work
# echo "---Install_aws_logging"
# #Install AWS logs
# Does not work in LZ, need to fix in next ticket
# echo "---Install AWS logging"
# sudo yum install wget openssl-devel bzip2-devel libffi-devel python-pip libpython-dev python-devel libpython-dev which initscripts cronie -y
# curl https://s3.amazonaws.com/aws-cloudwatch/downloads/latest/awslogs-agent-setup.py -O
# curl https://s3.amazonaws.com/aws-cloudwatch/downloads/latest/AgentDependencies.tar.gz -O
# sudo yum update rpm

#### setup_file_systems
echo "---setup_file_systems"

sudo yum install e2fsprogs

echo "Updating /etc/fstab file and mount"
cat <<EOT > /etc/fstab
/dev/VolGroup00/LogVol00	/	ext3	defaults	1 1
LABEL=/boot	/boot	ext3	defaults	1 2
tmpfs	/dev/shm	tmpfs	defaults	0 0
devpts	/dev/pts	devpts	gid=5,mode=620	0 0
sysfs	/sys	sysfs	defaults	0 0
proc	/proc	proc	defaults	0 0
/dev/VolGroup00/LogVol01	swap	swap	defaults	0 0
/dev/xvdf /oracle/dbf ext4 defaults 0 0
/dev/xvdg /stage ext4 defaults 0 0
/dev/xvdh /oracle/ar ext4 defaults 0 0
/dev/xvdi /oracle/software ext4 defaults 0 0
/dev/xvdj /oracle/temp_undo ext4 defaults 0 0
$EFS.efs.eu-west-2.amazonaws.com:/ /backups nfs4 rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2
EOT

# Create file systems 
sudo mkdir -p /oracle/dbf
sudo mkdir -p /stage
sudo mkdir -p /oracle/ar
sudo mkdir -p /oracle/software
sudo mkdir -p /oracle/temp_undo
sudo mkdir -p /backups

# #Mount all file systems in fstab
mount -a
chmod 777 /stage

#### setup_oracle_db_software
echo "---setup_oracle_db_software"
# Install wget / unzip
yum install -y unzip

# Create directories and set ownership
chown -R oracle:dba /oracle

#Update URL in bash profile
sed -i '/ORACLE_HOST/c\export ORACLE_HOST=${local.application_name}.${data.aws_route53_zone.external.name}' /home/oracle/.bash_profile

# Update permissions
chown oracle:dba /run/cfn-init/edw_warehouse.dbt
chmod 777 /run/cfn-init/edw_warehouse.dbt

# Check if the listener configuration file exists
if [ ! -f "/run/cfn-init/netca.rsp" ]; then
    echo "Listener response file does not exist. Skipping listener creation."
else
    # Check if the listener is already running
    if ! su oracle -l -c "lsnrctl status" | grep -q "Listener" ; then
        echo "Listener is not running. Creating listener and starting it..."

        # Ensure the response file has correct permissions
        chmod 777 /run/cfn-init/netca.rsp

        # Create the listener
        su oracle -l -c "netca /silent /responseFile /run/cfn-init/netca.rsp"

        # Start the listener
        su oracle -l -c "lsnrctl start"
    else
        echo "Listener is already running. Skipping listener creation and start."
    fi
fi

#### Prevent timeout on DB

# Increase ssh session timeout
sed -i 's/#ClientAliveInterval.*/ClientAliveInterval 1200/' /etc/ssh/sshd_config
sed -i 's/#ClientAliveCountMax.*/ClientAliveCountMax 5/' /etc/ssh/sshd_config
service sshd restart 


# Add TCP keepalive time to sysctl.conf ---> keepalive solution
echo "net.ipv4.tcp_keepalive_time = 120" >> /etc/sysctl.conf
sysctl -p

# Add SQLNET.EXPIRE_TIME to sqlnet.ora ---> keepalive solution
# Check if SQLNET.EXPIRE_TIME exists in the file and update it, otherwise add it
if grep -q "^SQLNET.EXPIRE_TIME" /oracle/software/product/10.2.0/network/admin/sqlnet.ora; then
    # If the line exists, update it to "SQLNET.EXPIRE_TIME = 2"
    sed -i 's/^SQLNET\.EXPIRE_TIME.*/SQLNET.EXPIRE_TIME = 2/' /oracle/software/product/10.2.0/network/admin/sqlnet.ora
else
    # If the line does not exist, append it to the end of the file
    echo "SQLNET.EXPIRE_TIME = 1" >> /oracle/software/product/10.2.0/network/admin/sqlnet.ora
fi

# Modify tnsnames.ora to insert (ENABLE=broken) ---> keepalive solution
grep -q '(ENABLE = broken)' /oracle/software/product/10.2.0/network/admin/tnsnames.ora || sed -i '/(DESCRIPTION =/a\\  (ENABLE = broken)' /oracle/software/product/10.2.0/network/admin/tnsnames.ora


sudo mkdir -p /var/opt/oracle
chown oracle:dba /var/opt/oracle
chown -R oracle:dba /home/oracle/edwcreate
chmod -R 777 /home/oracle/edwcreate
chown oracle:dba /var/opt/oracle/passwds.sql
chmod 777 /var/opt/oracle/passwds.sql
sed -i "s/tst/$ENV/g" /oracle/software/product/10.2.0/network/admin/tnsnames.ora
sed -i "0,/edw\./s/^.*edw\..*$/    (ADDRESS = (PROTOCOL = TCP)(HOST = ${local.application_name}.${data.aws_route53_zone.external.name})(PORT = 1521))/" /oracle/software/product/10.2.0/network/admin/tnsnames.ora
sed -i "0,/edw\.aws/s/^.*edw\.aws.*$/    (ADDRESS = (PROTOCOL = tcp)(HOST = ${local.application_name}.${data.aws_route53_zone.external.name})(PORT = 1521))/" /oracle/software/product/10.2.0/network/admin/tnsnames.ora
sed -i "0,/EDW/s/^.*EDW.*$/      (ADDRESS = (PROTOCOL = TCP)(HOST = ${local.application_name}.${data.aws_route53_zone.external.name})(PORT = 1521))/" /oracle/software/product/10.2.0/network/admin/listener.ora
sed -i "s/^\(define EDW_SYS=\).*/\1$(echo $SECRET | sed 's/[&/\]/\\&/g')/" /var/opt/oracle/passwds.sql
sed -i "s/^\(define EDW_SYSTEM=\).*/\1$(echo $SECRET | sed 's/[&/\]/\\&/g')/" /var/opt/oracle/passwds.sql

chown -R oracle:dba /home/oracle/scripts/
chmod -R 700 /home/oracle/scripts/
chown oracle:dba /home/oracle
chmod -R 777 /home/oracle

# Set permissions for staging directory
chmod -R 777 /stage/owb/

# Replace the secret in the rootrotate.sh script
sed -i "s|--secret-id .* --query|--secret-id ${aws_secretsmanager_secret.edw_db_ec2_root_secret.id} --query|g" /root/scripts/rootrotate.sh

#### setup_backups:

# setup efs backup mount point
sudo mkdir -p /home/oracle/backup_logs/
sudo mkdir -p /backups/$APPNAME_RMAN
chmod 777 /backups/EDW_RMAN
sed -i "s/\/backups\/production\/MIDB_RMAN\//\/backups\/$APPNAME_RMAN/g" /home/oracle/backup_scripts/rman_s3_arch_backup_v2_1.sh
sed -i "s/\/backups\/production\/MIDB_RMAN\//\/backups\/$APPNAME_RMAN/g" /home/oracle/backup_scripts/rman_full_backup.sh
chown -R oracle:dba /home/oracle/backup*
chmod -R 740 /home/oracle/backup*

# Create /etc/cron.d/backup_cron with the cron jobs
cat <<EOC3 > /etc/cron.d/backup_cron
0 */3 * * * /home/oracle/backup_scripts/rman_s3_arch_backup_v2_1.sh $APPNAME
0 06 * * 01 /home/oracle/backup_scripts/rman_full_backup.sh $APPNAME
00 07,10,13,16 * * * /home/oracle/scripts/freespace_alert.sh
00,15,30,45 * * * * /home/oracle/scripts/pmon_check.sh
# 0 7 * * 1 /home/oracle/scripts/maat_05365_ware_db_changes.sh
00 02 * * * /home/oracle/scripts/aws_ebs_backup.sh > /tmp/aws_ebs_backup.log
EOC3

chown root:root /etc/cron.d/backup_cron
chmod 644 /etc/cron.d/backup_cron

# Add backup_cron to crontab for oracle user
yes | cp -f /etc/cron.d/backup_cron /home/oracle/crecrontab.txt
chown oracle:dba /home/oracle/crecrontab.txt
chmod 744 /home/oracle/crecrontab.txt
su oracle -c "crontab /home/oracle/crecrontab.txt"

chown root:root /var/cw-custom.sh
chmod 700 /var/cw-custom.sh

# Create /etc/cron.d/custom_cloudwatch_metrics with the cron job
cat <<EOC4 > /etc/cron.d/custom_cloudwatch_metrics
*/1 * * * * root /var/cw-custom.sh
EOC4

chown root:root /etc/cron.d/custom_cloudwatch_metrics
chmod 600 /etc/cron.d/custom_cloudwatch_metrics

# alert_rota.sh - set permissions
chown oracle:dba /home/oracle/scripts/alert_rota.sh
chmod 755 /home/oracle/scripts/alert_rota.sh

# Create /etc/cron.d/oracle_rotation with the cron jobs
cat <<EOC5 > /etc/cron.d/oracle_rotation
00 07 * * * /home/oracle/scripts/alert_rota.sh $APPNAME
EOC5

chown root:root /etc/cron.d/oracle_rotation
chmod 644 /etc/cron.d/oracle_rotation

# Add oracle_rotation to crontab for oracle user
cat /etc/cron.d/oracle_rotation >> /home/oracle/crecrontab.txt
chown oracle:dba /home/oracle/crecrontab.txt
chmod 777 /home/oracle/crecrontab.txt
su oracle -c "crontab /home/oracle/crecrontab.txt"

#Update send mail URL 
echo "Update Sendmail configurations"
sed -i 's/${local.application_data.accounts[local.environment].old_mail_server_url}/${local.application_data.accounts[local.environment].laa_mail_relay_url}/g' /etc/mail/sendmail.cf
sed -i 's/${local.application_data.accounts[local.environment].old_domain_name}/${data.aws_route53_zone.external.name}/g' /etc/mail/sendmail.cf
sed -i 's/${local.application_data.accounts[local.environment].old_mail_server_url}/${local.application_data.accounts[local.environment].laa_mail_relay_url}/g' /etc/mail/sendmail.mc
sed -i 's/${local.application_data.accounts[local.environment].old_domain_name}/${data.aws_route53_zone.external.name}/g' /etc/mail/sendmail.mc
/etc/init.d/sendmail restart

sudo su - oracle -c "sqlplus / as sysdba << EOC6
shutdown abort;
startup;
exit;
EOC6"

EOF
}

####### IAM role #######

resource "aws_iam_role" "edw_ec2_role" {
  name = "${local.application_name}-ec2-instance-role"
  tags = merge(
    local.tags,
    {
      Name = "${local.application_name}-ec2-instance-role"
    }
  )
  path               = "/"
  assume_role_policy = <<EOF
{

    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": "sts:AssumeRole",
            "Principal": {
               "Service": "ec2.amazonaws.com"
            },
            "Effect": "Allow",
            "Sid": ""
        }
    ]
}
EOF
}

###### DB Instance Profile ########

resource "aws_iam_instance_profile" "edw_ec2_instance_profile" {
  name = "${local.application_name}-S3-${local.application_data.accounts[local.environment].edw_bucket_name}-edw-RW-ec2-profile"
  role = aws_iam_role.edw_ec2_role.name
  tags = merge(
    local.tags,
    {
      Name = "${local.application_name}-ec2-instance-profile"
    }
  )
}

####### DB Policy #######

resource "aws_iam_policy" "edw_ec2_role_policy" {
  name = "${local.application_name}-ec2-policy2"
  path = "/"
  tags = merge(
    local.tags,
    {
      Name = "${local.application_name}-ec2-policy"
    }
  )
  policy = <<EOF
{
    "Version" : "2012-10-17",
      "Statement": [
        {
            "Action": [
                "s3:ListBucket"
            ],
            "Resource": [
                "arn:aws:s3:::laa-software-library",
                "arn:aws:s3:::laa-software-library/*"
            ],
            "Effect": "Allow"
        },
        {
            "Action": [
                "s3:GetObject"
            ],
            "Resource": [
                "arn:aws:s3:::laa-software-library/*"
            ],
            "Effect": "Allow"
        }, 
        {
            "Action": [
                "secretsmanager:GetSecretValue"
            ],
            "Resource": [
                "arn:aws:secretsmanager:${data.aws_region.current.name}:${data.aws_caller_identity.current.account_id}:secret:${local.application_name}/app/*"
            ],
            "Effect": "Allow"
        },  
        {
            "Action": [
                "logs:CreateLogGroup",
                "logs:CreateLogStream",
                "logs:DescribeLogStreams",
                "logs:PutRetentionPolicy",
                "logs:PutLogEvents"
            ],
            "Resource": ["*"],
            "Effect": "Allow"
        },
        {
            "Action": [
                "ec2:DescribeInstances",            
                "ec2:CreateSnapshots"
            ],
            "Resource": ["*"],
            "Effect": "Allow"
        },         
        {
            "Action": [
                "ec2:CreateTags"
            ],
            "Resource": ["*"],
            "Effect": "Allow"
        }
    ]
}
EOF
}


####### DB Policy attachments ########

resource "aws_iam_role_policy_attachment" "edw_cw_agent_policy_attachment" {
  role       = aws_iam_role.edw_ec2_role.name
  policy_arn = "arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy"
}

resource "aws_iam_role_policy_attachment" "edw_ec2_policy_attachments" {
  role       = aws_iam_role.edw_ec2_role.name
  policy_arn = aws_iam_policy.edw_ec2_role_policy.arn
}

####### DB Instance #######

resource "aws_key_pair" "edw_ec2_key" {
  key_name   = "${local.application_name}-ssh-key-new"
  public_key = local.application_data.accounts[local.environment].edw_ec2_key
}

resource "aws_instance" "edw_db_instance" {
  ami                         = local.application_data.accounts[local.environment].edw_ec2_ami_id
  availability_zone           = "eu-west-2a"
  instance_type               = local.application_data.accounts[local.environment].edw_ec2_instance_type
  iam_instance_profile        = aws_iam_instance_profile.edw_ec2_instance_profile.id
  key_name                    = aws_key_pair.edw_ec2_key.key_name
  subnet_id                   = data.aws_subnet.private_subnets_a.id
  vpc_security_group_ids      = [aws_security_group.edw_db_security_group.id]
  user_data_base64            = base64encode(local.db_userdata)
  user_data_replace_on_change = true

  root_block_device {
    tags = merge(
      local.tags,
      { "Name" = "${local.application_name}-root-volume" }
    )
  }

  metadata_options {
    http_endpoint               = "enabled"
    http_put_response_hop_limit = 2
    http_tokens                 = "optional"
  }

  lifecycle {
    create_before_destroy = true
  }

  tags = merge(
    local.tags,
    { "Name" = local.application_data.accounts[local.environment].database_ec2_name },
    { "instance-scheduling" = "skip-scheduling" }
  )
}

####### DB Volumes #######

resource "aws_ebs_volume" "orahomeVolume" {
  availability_zone = "${local.application_data.accounts[local.environment].edw_region}a"
  size              = local.application_data.accounts[local.environment].edw_OrahomeVolumeSize
  encrypted         = true
  type              = "gp3"
  kms_key_id        = data.aws_kms_key.ebs_shared.key_id
  snapshot_id       = local.application_data.accounts[local.environment].orahome_snapshot_id # This is used for when data is being migrated

  lifecycle {
    ignore_changes = [kms_key_id]
  }

  tags = {
    Name = "${local.application_name}-orahome"
  }
}

resource "aws_volume_attachment" "orahomeVolume-attachment" {
  device_name = "/dev/sdi"
  volume_id   = aws_ebs_volume.orahomeVolume.id
  instance_id = aws_instance.edw_db_instance.id
}

resource "aws_ebs_volume" "oratempVolume" {
  availability_zone = "${local.application_data.accounts[local.environment].edw_region}a"
  size              = local.application_data.accounts[local.environment].edw_OratempVolumeSize
  encrypted         = true
  type              = "gp3"
  kms_key_id        = data.aws_kms_key.ebs_shared.key_id
  snapshot_id       = local.application_data.accounts[local.environment].oraredo_snapshot_id # This is used for when data is being migrated

  lifecycle {
    ignore_changes = [kms_key_id]
  }

  tags = {
    Name = "${local.application_name}-oraredo"
  }
}

resource "aws_volume_attachment" "oratempVolume-attachment" {
  device_name = "/dev/sdj"
  volume_id   = aws_ebs_volume.oratempVolume.id
  instance_id = aws_instance.edw_db_instance.id
}

resource "aws_ebs_volume" "oradataVolume" {
  availability_zone = "${local.application_data.accounts[local.environment].edw_region}a"
  size              = local.application_data.accounts[local.environment].edw_OradataVolumeSize
  encrypted         = true
  type              = "gp3"
  kms_key_id        = data.aws_kms_key.ebs_shared.key_id
  snapshot_id       = local.application_data.accounts[local.environment].oradata_snapshot_id # This is used for when data is being migrated

  lifecycle {
    ignore_changes = [kms_key_id]
  }

  tags = {
    Name = "${local.application_name}-oradata"
  }
}

resource "aws_volume_attachment" "oradataVolume-attachment" {
  device_name = "/dev/sdf"
  volume_id   = aws_ebs_volume.oradataVolume.id
  instance_id = aws_instance.edw_db_instance.id
}

resource "aws_ebs_volume" "softwareVolume" {
  availability_zone = "${local.application_data.accounts[local.environment].edw_region}a"
  size              = local.application_data.accounts[local.environment].edw_SoftwareVolumeSize
  encrypted         = true
  type              = "gp3"
  kms_key_id        = data.aws_kms_key.ebs_shared.key_id
  snapshot_id       = local.application_data.accounts[local.environment].software_snapshot_id # This is used for when data is being migrated

  lifecycle {
    ignore_changes = [kms_key_id]
  }

  tags = {
    Name = "${local.application_name}-software"
  }
}

resource "aws_volume_attachment" "softwareVolume-attachment" {
  device_name = "/dev/sdg"
  volume_id   = aws_ebs_volume.softwareVolume.id
  instance_id = aws_instance.edw_db_instance.id
}

resource "aws_ebs_volume" "ArchiveVolume" {
  availability_zone = "${local.application_data.accounts[local.environment].edw_region}a"
  size              = local.application_data.accounts[local.environment].edw_ArchiveVolumeSize
  encrypted         = true
  type              = "gp3"
  kms_key_id        = data.aws_kms_key.ebs_shared.key_id
  snapshot_id       = local.application_data.accounts[local.environment].oraarch_snapshot_id # This is used for when data is being migrated

  lifecycle {
    ignore_changes = [kms_key_id]
  }

  tags = {
    Name                                               = "${local.application_name}-oraarch"
    "dlm:snapshot-with:volume-hourly-35-day-retention" = "yes"
  }
}

resource "aws_volume_attachment" "ArchiveVolume-attachment" {
  device_name = "/dev/sdh"
  volume_id   = aws_ebs_volume.ArchiveVolume.id
  instance_id = aws_instance.edw_db_instance.id
}


######## DB Security Groups #######

resource "aws_security_group" "edw_db_security_group" {
  name        = "${local.application_name}-Security Group"
  description = "Security Group for DB EC2 instance"
  vpc_id      = data.aws_vpc.shared.id

  tags = merge(
    local.tags,
    {
      Name = "${local.application_name}-security-group"
    }
  )
}

resource "aws_vpc_security_group_ingress_rule" "db_bastion_ssh" {
  security_group_id            = aws_security_group.edw_db_security_group.id
  description                  = "SSH from the Bastion"
  referenced_security_group_id = module.bastion_linux.bastion_security_group
  from_port                    = 22
  ip_protocol                  = "tcp"
  to_port                      = 22
}

resource "aws_vpc_security_group_ingress_rule" "db_lambda" {
  security_group_id            = aws_security_group.edw_db_security_group.id
  description                  = "Allow Lambda SSH access for backup snapshots"
  referenced_security_group_id = aws_security_group.backup_lambda.id
  from_port                    = 22
  ip_protocol                  = "tcp"
  to_port                      = 22
}

resource "aws_vpc_security_group_ingress_rule" "RDS_Appstream" {
  security_group_id = aws_security_group.edw_db_security_group.id
  description       = "RDS Appstream access"
  cidr_ipv4         = "10.200.32.0/19"
  from_port         = 1521
  ip_protocol       = "tcp"
  to_port           = 1521
}

resource "aws_vpc_security_group_ingress_rule" "RDS_workstream" {
  security_group_id = aws_security_group.edw_db_security_group.id
  description       = "RDS Workspace access"
  cidr_ipv4         = local.application_data.accounts[local.environment].edw_management_cidr
  from_port         = 1521
  ip_protocol       = "tcp"
  to_port           = 1521
}

resource "aws_vpc_security_group_ingress_rule" "RDS_env" {
  security_group_id = aws_security_group.edw_db_security_group.id
  description       = "RDS env access"
  cidr_ipv4         = data.aws_vpc.shared.cidr_block
  from_port         = 1521
  ip_protocol       = "tcp"
  to_port           = 1521
}

resource "aws_vpc_security_group_egress_rule" "all_out" {
  security_group_id = aws_security_group.edw_db_security_group.id
  cidr_ipv4         = "0.0.0.0/0"
  ip_protocol       = "-1"
}


###### DB DNS #######

resource "aws_route53_record" "edw_internal_dns_record" {
  provider = aws.core-vpc
  zone_id  = data.aws_route53_zone.external.zone_id
  name     = "${local.application_name}.${data.aws_route53_zone.external.name}"
  type     = "A"
  ttl      = 900
  records  = [aws_instance.edw_db_instance.private_ip]
}