#!/bin/bash
sudo rm /etc/nginx/sites-enabled/*
sudo ln -s /etc/nginx/sites-available/adjudicationpanel.tribunals.gov.uk /etc/nginx/sites-enabled/
sudo ln -s /etc/nginx/sites-available/administrativeappeals.tribunals.gov.uk /etc/nginx/sites-enabled/
sudo ln -s /etc/nginx/sites-available/ahmlr.gov.uk /etc/nginx/sites-enabled/
sudo ln -s /etc/nginx/sites-available/appeals-service.gov.uk /etc/nginx/sites-enabled/
sudo ln -s /etc/nginx/sites-available/asylum-support-tribunal.gov.uk /etc/nginx/sites-enabled/
sudo ln -s /etc/nginx/sites-available/carestandardstribunal.gov.uk /etc/nginx/sites-enabled/
sudo ln -s /etc/nginx/sites-available/charity.tribunals.gov.uk /etc/nginx/sites-enabled/
sudo ln -s /etc/nginx/sites-available/cicap.gov.uk /etc/nginx/sites-enabled/
sudo ln -s /etc/nginx/sites-available/civilappeals.gov.uk /etc/nginx/sites-enabled/
sudo ln -s /etc/nginx/sites-available/cjit.gov.uk /etc/nginx/sites-enabled/
sudo ln -s /etc/nginx/sites-available/cjsdigitalmodel.org /etc/nginx/sites-enabled/
sudo ln -s /etc/nginx/sites-available/cjs.gov.uk /etc/nginx/sites-enabled/
sudo ln -s /etc/nginx/sites-available/cjsonline.gov.uk /etc/nginx/sites-enabled/
sudo ln -s /etc/nginx/sites-available/_compiled /etc/nginx/sites-enabled/
sudo ln -s /etc/nginx/sites-available/complaints.judicialconduct.gov.uk /etc/nginx/sites-enabled/
sudo ln -s /etc/nginx/sites-available/consumercreditappeals.tribunals.gov.uk /etc/nginx/sites-enabled/
sudo ln -s /etc/nginx/sites-available/courtfines.justice.gov.uk /etc/nginx/sites-enabled/
sudo ln -s /etc/nginx/sites-available/courtfunds.gov.uk /etc/nginx/sites-enabled/
sudo ln -s /etc/nginx/sites-available/criminal-justice-system.gov.uk /etc/nginx/sites-enabled/
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
sudo ln -s /etc/nginx/sites-available/dugganinquest.independent.gov.uk /etc/nginx/sites-enabled/
sudo ln -s /etc/nginx/sites-available/employmentappeals.gov.uk /etc/nginx/sites-enabled/
sudo ln -s /etc/nginx/sites-available/estateagentappeals.tribunals.gov.uk /etc/nginx/sites-enabled/
sudo ln -s /etc/nginx/sites-available/fhsaa.tribunals.gov.uk /etc/nginx/sites-enabled/
sudo ln -s /etc/nginx/sites-available/financeandtaxtribunals.gov.uk /etc/nginx/sites-enabled/
sudo ln -s /etc/nginx/sites-available/hillsboroughinquests.independent.gov.uk /etc/nginx/sites-enabled/
sudo ln -s /etc/nginx/sites-available/immigrationservicestribunal.gov.uk /etc/nginx/sites-enabled/
sudo ln -s /etc/nginx/sites-available/informationtribunal.dsd.io /etc/nginx/sites-enabled/
sudo ln -s /etc/nginx/sites-available/informationtribunal.gov.uk /etc/nginx/sites-enabled/
sudo ln -s /etc/nginx/sites-available/judicialombudsman.gov.uk /etc/nginx/sites-enabled/
sudo ln -s /etc/nginx/sites-available/landstribunal.gov.uk /etc/nginx/sites-enabled/
sudo ln -s /etc/nginx/sites-available/obr.co.uk /etc/nginx/sites-enabled/
sudo ln -s /etc/nginx/sites-available/osscsc.gov.uk /etc/nginx/sites-enabled/
sudo ln -s /etc/nginx/sites-available/paroleboard.gov.uk /etc/nginx/sites-enabled/
sudo ln -s /etc/nginx/sites-available/sendmoneytoaprisoner.justice.gov.uk /etc/nginx/sites-enabled/
sudo ln -s /etc/nginx/sites-available/siac.tribunals.gov.uk /etc/nginx/sites-enabled/
sudo ln -s /etc/nginx/sites-available/trackmycrime.net /etc/nginx/sites-enabled/
sudo ln -s /etc/nginx/sites-available/transporttribunal.gov.uk /etc/nginx/sites-enabled/
sudo ln -s /etc/nginx/sites-available/tribunals.gov.uk /etc/nginx/sites-enabled/
sudo ln -s /etc/nginx/sites-available/yjbpublications.justice.gov.uk /etc/nginx/sites-enabled/
sudo ln -s /etc/nginx/sites-available/landregistrationdivision.tribunals.hmcts-development.modernisation-platform.service.justice.gov.uk /etc/nginx/sites-enabled/
sudo ln -s /etc/nginx/sites-available/administrativeappeals.decisions.tribunals.gov.uk /etc/nginx/sites-enabled/
sudo ln -s /etc/nginx/sites-available/carestandards.decisions.tribunals.gov.uk /etc/nginx/sites-enabled/
sudo ln -s /etc/nginx/sites-available/cicap.decisions.tribunals.gov.uk /etc/nginx/sites-enabled/
sudo ln -s /etc/nginx/sites-available/employmentappeals.decisions.tribunals.gov.uk /etc/nginx/sites-enabled/
sudo ln -s /etc/nginx/sites-available/financeandtax.decisions.tribunals.gov.uk /etc/nginx/sites-enabled/
sudo ln -s /etc/nginx/sites-available/immigrationservices.decisions.tribunals.gov.uk /etc/nginx/sites-enabled/
sudo ln -s /etc/nginx/sites-available/informationrights.decisions.tribunals.gov.uk /etc/nginx/sites-enabled/
sudo ln -s /etc/nginx/sites-available/landregistrationdivision.decisions.tribunals.gov.uk /etc/nginx/sites-enabled/
sudo ln -s /etc/nginx/sites-available/landschamber.decisions.tribunals.gov.uk /etc/nginx/sites-enabled/
sudo ln -s /etc/nginx/sites-available/transportappeals.decisions.tribunals.gov.uk /etc/nginx/sites-enabled/
sudo ln -s /etc/nginx/sites-available/adminappeals.reports.tribunals.gov.uk /etc/nginx/sites-enabled/
sudo ln -s /etc/nginx/sites-available/charity.decisions.tribunals.gov.uk /etc/nginx/sites-enabled/
sudo ln -s /etc/nginx/sites-available/claimsmanagement.decisions.tribunals.gov.uk /etc/nginx/sites-enabled/
sudo ln -s /etc/nginx/sites-available/consumercreditappeals.decisions.tribunals.gov.uk /etc/nginx/sites-enabled/
sudo ln -s /etc/nginx/sites-available/estateagentappeals.decisions.tribunals.gov.uk /etc/nginx/sites-enabled/
sudo ln -s /etc/nginx/sites-available/phl.decisions.tribunals.gov.uk /etc/nginx/sites-enabled/
sudo ln -s /etc/nginx/sites-available/siac.decisions.tribunals.gov.uk /etc/nginx/sites-enabled/
sudo ln -s /etc/nginx/sites-available/sscs.venues.tribunals.gov.uk /etc/nginx/sites-enabled/
sudo ln -s /etc/nginx/sites-available/taxandchancery_ut.decisions.tribunals.gov.uk /etc/nginx/sites-enabled/
sudo ln -s /etc/nginx/sites-available/tax.decisions.tribunals.gov.uk /etc/nginx/sites-enabled/