skip-check:
  - CKV_AWS_126 # skip "Ensure that detailed monitoring is enabled for EC2 instances", not required for now
  - CKV_AWS_189 # skip "Ensure EBS Volume is encrypted by KMS using a customer managed Key (CMK)"
