---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: default-certificate
spec:
  secretName: default-certificate
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production
  commonName: {{ quote .Values.defaultCertficate.dnsName }}
  dnsNames:
    - {{ quote .Values.defaultCertficate.dnsName }}
