on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
env:
  AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_IN_AUTOMATION: true
jobs:
  go-tests:
    name: Run Go Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - uses: hashicorp/setup-terraform@v2.0.2
        with:
          terraform_version: 1.0.1
          terraform_wrapper: false
      - name: set terraform workspace
        run: |
          #CONFIGURE TERRAFORM AND WORKSPACE
          terraform -chdir="test/unit-test" init
          terraform -chdir="test/unit-test" workspace select testing-test
      - name: Download Go Modules
        working-directory: test
        run: go mod download
      - name: Run Go Tests
        working-directory: test
        run: go test -v
       
