# Application secrets injected into the ECS task as environment variables.
#
# Two families of secret today:
#
#   * MPAPB_SECRET_KEY -- signs the auth + CSRF cookies. UI-specific, so we
#     create it locally. Auto-generated by ``random_password`` on first
#     apply; operators can rotate via the AWS console without Terraform
#     clobbering the value on the next apply.
#
#   * GitHub App credentials (installation id + private key PEM) -- created
#     locally as empty containers; values are populated out-of-band via the
#     AWS console/CLI after ``terraform apply`` provisions them. Terraform
#     never sees the plaintext (there is no ``aws_secretsmanager_secret_version``
#     for these). The ECS task fails to start until they are populated,
#     which is the intended behaviour.

# ---------- MPAPB_SECRET_KEY ----------

resource "random_password" "mpapb_secret_key" {
  length  = 64
  special = false # base64-safe alphabet is plenty for cookie signing
}

resource "aws_secretsmanager_secret" "mpapb_secret_key" {
  # checkov:skip=CKV2_AWS_57:This secret is an itsdangerous cookie-signing key
  # loaded at ECS task-start; Secrets Manager scheduled rotation would
  # invalidate every active user session mid-request. Rotation is performed
  # manually via a task restart, and secret_string is ignored on updates
  # (see aws_secretsmanager_secret_version.mpapb_secret_key below).
  # checkov:skip=CKV_AWS_149:Encrypted at rest with the AWS-managed
  # ``aws/secretsmanager`` KMS key. A customer-managed CMK adds cost + key
  # rotation ops disproportionate to a prototype cookie-signing key that is
  # only ever read by a single ECS execution role in this account.
  name                    = "${local.application_name}-ui/mpapb-secret-key"
  description             = "itsdangerous signing key for the AI Prototype Builder UI cookies"
  recovery_window_in_days = 7
  tags                    = local.tags
}

resource "aws_secretsmanager_secret_version" "mpapb_secret_key" {
  secret_id     = aws_secretsmanager_secret.mpapb_secret_key.id
  secret_string = random_password.mpapb_secret_key.result

  lifecycle {
    # Allow out-of-band rotation via the AWS console / CLI without Terraform
    # trying to reset the value on the next plan.
    ignore_changes = [secret_string]
  }
}

# ---------- GitHub App credentials ----------
#
# Empty containers; populate the values in the AWS console (or via CLI)
# after ``terraform apply`` creates them. Deliberately no
# ``aws_secretsmanager_secret_version`` here so Terraform never handles
# the plaintext PEM.

resource "aws_secretsmanager_secret" "github_app_installation_id" {
  # checkov:skip=CKV2_AWS_57:Value is managed externally (MoJ GitHub App owned
  # by the org). Secrets Manager scheduled rotation cannot rotate an
  # externally-owned installation id; a custom rotator Lambda would just
  # re-fetch the same value.
  # checkov:skip=CKV_AWS_149:Encrypted at rest with the AWS-managed
  # ``aws/secretsmanager`` KMS key. The stored value is a public numeric id
  # (visible in GitHub App settings); a customer-managed CMK adds cost + key
  # rotation ops without a proportionate confidentiality benefit.
  name                    = "${local.application_name}-ui/github-app-installation-id"
  description             = "Numeric GitHub App installation id for the MoJ Modernisation Platform App. Populate manually after apply."
  recovery_window_in_days = 7
  tags                    = local.tags
}

resource "aws_secretsmanager_secret" "github_app_private_key" {
  # checkov:skip=CKV2_AWS_57:Value is managed externally (MoJ GitHub App owned
  # by the org). Secrets Manager scheduled rotation cannot rotate an
  # externally-owned private key; rotation happens on the GitHub side and is
  # mirrored here manually.
  # checkov:skip=CKV_AWS_149:Encrypted at rest with the AWS-managed
  # ``aws/secretsmanager`` KMS key. The PEM is read exclusively by a single
  # ECS execution role in this account; a customer-managed CMK adds cost +
  # key rotation ops disproportionate to the prototype threat model.
  name                    = "${local.application_name}-ui/github-app-private-key"
  description             = "PEM-encoded private key for the MoJ Modernisation Platform GitHub App. Populate manually after apply."
  recovery_window_in_days = 7
  tags                    = local.tags
}

# ---------- Execution role IAM ----------
#
# The execution role pulls secrets at task-start time and injects them as
# env vars. It needs GetSecretValue on all three local secrets.

data "aws_iam_policy_document" "ecs_task_execution_secrets" {

  statement {
    sid    = "ReadAppSecrets"
    effect = "Allow"
    actions = [
      "secretsmanager:GetSecretValue",
    ]
    resources = [
      aws_secretsmanager_secret.mpapb_secret_key.arn,
      aws_secretsmanager_secret.github_app_installation_id.arn,
      aws_secretsmanager_secret.github_app_private_key.arn,
    ]
  }

  dynamic "statement" {
    for_each = local.in_app_oidc_count == 1 ? [1] : []
    content {
      sid    = "ReadEntraOidcSecretsForInApp"
      effect = "Allow"
      actions = [
        "secretsmanager:GetSecretValue",
      ]
      resources = [
        aws_secretsmanager_secret.entra_oidc_tenant_id[0].arn,
        aws_secretsmanager_secret.entra_oidc_client_id[0].arn,
        aws_secretsmanager_secret.entra_oidc_client_secret[0].arn,
      ]
    }
  }
}

resource "aws_iam_role_policy" "ecs_task_execution_secrets" {
  name   = "read-app-secrets"
  role   = aws_iam_role.ecs_task_execution.id
  policy = data.aws_iam_policy_document.ecs_task_execution_secrets.json
}
