---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ai-gateway-internal
  namespace: {{ .Release.Namespace }}
spec:
  hostnames:
    - {{ .Values.internalHostname }}
  parentRefs:
    - name: ai-gateway-internal
      sectionName: https
  rules:
    - backendRefs:
        - name: litellm
          port: 4000

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ai-gateway-internal-http-redirect
  namespace: {{ .Release.Namespace }}
spec:
  hostnames:
    - {{ .Values.internalHostname }}
  parentRefs:
    - name: ai-gateway-internal
      sectionName: http
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            port: 443
            statusCode: 301
