skip-checks:
  - CKV_TF_1 # Module version is sufficient
  - CKV_AWS_91 # Not all LBs require logging
  - CKV_AWS_150 # Deletion protetion on every load balancer is unnecessary
  - CKV_AWS_152 # Cross-zone load-balancing unecessary
  - CKV_AWS_337 # SSM parameters using default KMS key (alias/aws/ssm)
