skip-check:
  # Failed
  - CKV_AWS_50 # "X-Ray tracing is enabled for Lambda"
  - CKV_AWS_290 # "Ensure IAM policies does not allow write access without constraints"
  - CKV_AWS_330 # "EFS access points should enforce a user identity"
  - CKV_AWS_329 # "EFS access points should enforce a root directory"
  - CKV_AWS_355 # "Ensure no IAM policies documents allow "*" as a statement's resource for restrictable actions"
  - CKV_AWS_40 # "Ensure IAM policies are attached only to groups or roles (Reducing access management complexity may in-turn reduce opportunity for a principal to inadvertently receive or retain excessive privileges.)"
  - CKV_AWS_284 # "Ensure State Machine has X-Ray tracing enabled"
  - CKV_AWS_66 # "Ensure that CloudWatch Log Group specifies retention days"
  - CKV_AWS_273 # "Ensure access is controlled through SSO and not AWS IAM defined users"
  - CKV_AWS_26 # "Ensure all data stored in the SNS topic is encrypted"
  - CKV_AWS_111 # "Ensure IAM policies does not allow write access without constraints"
  - CKV_AWS_108 # "Ensure IAM policies does not allow data exfiltration"
  - CKV_AWS_338 # "Ensure CloudWatch log groups retains logs for at least 1 year"
  - CKV_AWS_158 # "Ensure that CloudWatch Log Group is encrypted by KMS"
  - CKV_AWS_337 # "Ensure SSM parameters are using KMS CMK"
  - CKV_AWS_117 # "Ensure that AWS Lambda function is configured inside a VPC"
  - CKV_AWS_116 # "Ensure that AWS Lambda function is configured for a Dead Letter Queue(DLQ)"
  - CKV_AWS_152 # "Ensure that Load Balancer (Network/Gateway) has cross-zone load balancing enabled"
  - CKV_AWS_115 # "Ensure that AWS Lambda function is configured for function-level concurrent execution limit"
  - CKV_AWS_173 # "Check encryption settings for Lambda environmental variable"
  - CKV_TF_1 # "Ensure Terraform module sources use a commit hash"
  - CKV_AWS_356 # "Ensure no IAM policies documents allow "*" as a statement's resource for restrictable actions"
  - CKV_AWS_272 # "Ensure AWS Lambda function is configured to validate code-signing"
  - CKV_AWS_150 # "Ensure that Load Balancer has deletion protection enabled"
  - CKV_AWS_91 # "Ensure the ELBv2 (Application/Network) has access logging enabled"
