---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: airflow-high-memory
spec:
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 5m
  template:
    metadata:
      labels:
        compute.analytical-platform.service.justice.gov.uk/karpenter-node-pool: "airflow-high-memory"
    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: bottlerocket-general
      taints:
        - key: compute.analytical-platform.service.justice.gov.uk/karpenter-node-pool
          value: "airflow-high-memory"
          effect: NoSchedule
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]
        - key: karpenter.k8s.aws/instance-family
          operator: In
          values: ["r6i", "r7i"]
