---
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: gpu-on-demand
spec:
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 5m
  template:
    metadata:
      labels:
        compute.analytical-platform.service.justice.gov.uk/karpenter-node-pool: "gpu-on-demand"
    spec:
      nodeClassRef:
        apiVersion: karpenter.k8s.aws/v1beta1
        kind: EC2NodeClass
        name: bottlerocket-gpu
      taints:
        - key: compute.analytical-platform.service.justice.gov.uk/karpenter-node-pool
          value: "gpu-on-demand"
          effect: NoSchedule
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]
        - key: node.kubernetes.io/instance-type
          operator: In
          values: ["p3.2xlarge"]