apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: custom-proxy-config
  namespace: default
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyDeployment:
        replicas: 2
      envoyService:
        annotations:
          service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
          service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
          service.beta.kubernetes.io/aws-load-balancer-name: envoy-gw-nlb
          # TODO: see if we can use the auto discovery rather than explicitly declaring
          # https://repost.aws/knowledge-center/load-balancer-troubleshoot-creating
          service.beta.kubernetes.io/aws-load-balancer-subnets: subnet-0df18aac4d4a98b34,subnet-0e25a0b8430a0c7d8,subnet-0901fe8be978042a4
