formatter: "markdown table"

sections:
  show:
    - header
    - inputs
    - outputs

output:
  file: "README.md"
  mode: replace
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS --> 
