#!/bin/bash

# --- AWS ---
terraform state mv  -state=../root_dev.tfstate -state-out=cluster_dev.tfstate  "aws_iam_service_linked_role.spot"  "aws_iam_service_linked_role.spot"

# --- HELM_RELEASE ---
terraform state mv  -state=../root_dev.tfstate -state-out=cluster_dev.tfstate  "helm_release.amazon_prometheus_proxy"   "helm_release.amazon_prometheus_proxy"
terraform state mv  -state=../root_dev.tfstate -state-out=cluster_dev.tfstate  "helm_release.aws_cloudwatch_metrics"   "helm_release.aws_cloudwatch_metrics"
terraform state mv  -state=../root_dev.tfstate -state-out=cluster_dev.tfstate  "helm_release.aws_for_fluent_bit"   "helm_release.aws_for_fluent_bit"
terraform state mv  -state=../root_dev.tfstate -state-out=cluster_dev.tfstate  "helm_release.cert_manager"   "helm_release.cert_manager"
terraform state mv  -state=../root_dev.tfstate -state-out=cluster_dev.tfstate  "helm_release.cert_manager_issuers"   "helm_release.cert_manager_issuers"
terraform state mv  -state=../root_dev.tfstate -state-out=cluster_dev.tfstate  "helm_release.cluster_autoscaler"   "helm_release.cluster_autoscaler"
terraform state mv  -state=../root_dev.tfstate -state-out=cluster_dev.tfstate  "helm_release.external_dns"   "helm_release.external_dns"
terraform state mv  -state=../root_dev.tfstate -state-out=cluster_dev.tfstate  "helm_release.external_secrets"   "helm_release.external_secrets"
terraform state mv  -state=../root_dev.tfstate -state-out=cluster_dev.tfstate  "helm_release.external_secrets_cluster_secret_store"   "helm_release.external_secrets_cluster_secret_store"
terraform state mv  -state=../root_dev.tfstate -state-out=cluster_dev.tfstate  "helm_release.ingress_nginx"   "helm_release.ingress_nginx"
terraform state mv  -state=../root_dev.tfstate -state-out=cluster_dev.tfstate  "helm_release.ingress_nginx_default_certificate"   "helm_release.ingress_nginx_default_certificate"
terraform state mv  -state=../root_dev.tfstate -state-out=cluster_dev.tfstate  "helm_release.karpenter"   "helm_release.karpenter"
terraform state mv  -state=../root_dev.tfstate -state-out=cluster_dev.tfstate  "helm_release.karpenter_configuration"   "helm_release.karpenter_configuration"
terraform state mv  -state=../root_dev.tfstate -state-out=cluster_dev.tfstate  "helm_release.karpenter_crd"   "helm_release.karpenter_crd"
terraform state mv  -state=../root_dev.tfstate -state-out=cluster_dev.tfstate  "helm_release.keda"   "helm_release.keda"
terraform state mv  -state=../root_dev.tfstate -state-out=cluster_dev.tfstate  "helm_release.kyverno"   "helm_release.kyverno"

# --- KUBERNETES ---
terraform state mv  -state=../root_dev.tfstate -state-out=cluster_dev.tfstate  "kubernetes_annotations.gp2"   "kubernetes_annotations.gp2"
terraform state mv  -state=../root_dev.tfstate -state-out=cluster_dev.tfstate  "kubernetes_cluster_role.mwaa_external_secrets"   "kubernetes_cluster_role.mwaa_external_secrets"
terraform state mv  -state=../root_dev.tfstate -state-out=cluster_dev.tfstate  "kubernetes_cluster_role_binding.mwaa_external_secrets"   "kubernetes_cluster_role_binding.mwaa_external_secrets"
terraform state mv  -state=../root_dev.tfstate -state-out=cluster_dev.tfstate  "kubernetes_manifest.eso_secretstore_data_production"   "kubernetes_manifest.eso_secretstore_data_production"
terraform state mv  -state=../root_dev.tfstate -state-out=cluster_dev.tfstate  "kubernetes_manifest.prometheus_operator_crds[\"alertmanagerconfigs\"]"   "kubernetes_manifest.prometheus_operator_crds[\"alertmanagerconfigs\"]"
terraform state mv  -state=../root_dev.tfstate -state-out=cluster_dev.tfstate  "kubernetes_manifest.prometheus_operator_crds[\"alertmanagers\"]"   "kubernetes_manifest.prometheus_operator_crds[\"alertmanagers\"]"
terraform state mv  -state=../root_dev.tfstate -state-out=cluster_dev.tfstate  "kubernetes_manifest.prometheus_operator_crds[\"podmonitors\"]"   "kubernetes_manifest.prometheus_operator_crds[\"podmonitors\"]"
terraform state mv  -state=../root_dev.tfstate -state-out=cluster_dev.tfstate  "kubernetes_manifest.prometheus_operator_crds[\"probes\"]"   "kubernetes_manifest.prometheus_operator_crds[\"probes\"]"
terraform state mv  -state=../root_dev.tfstate -state-out=cluster_dev.tfstate  "kubernetes_manifest.prometheus_operator_crds[\"prometheus_agents\"]"   "kubernetes_manifest.prometheus_operator_crds[\"prometheus_agents\"]"
terraform state mv  -state=../root_dev.tfstate -state-out=cluster_dev.tfstate  "kubernetes_manifest.prometheus_operator_crds[\"prometheuses\"]"   "kubernetes_manifest.prometheus_operator_crds[\"prometheuses\"]"
terraform state mv  -state=../root_dev.tfstate -state-out=cluster_dev.tfstate  "kubernetes_manifest.prometheus_operator_crds[\"prometheusrules\"]"   "kubernetes_manifest.prometheus_operator_crds[\"prometheusrules\"]"
terraform state mv  -state=../root_dev.tfstate -state-out=cluster_dev.tfstate  "kubernetes_manifest.prometheus_operator_crds[\"scrapeconfigs\"]"   "kubernetes_manifest.prometheus_operator_crds[\"scrapeconfigs\"]"
terraform state mv  -state=../root_dev.tfstate -state-out=cluster_dev.tfstate  "kubernetes_manifest.prometheus_operator_crds[\"servicemonitors\"]"   "kubernetes_manifest.prometheus_operator_crds[\"servicemonitors\"]"
terraform state mv  -state=../root_dev.tfstate -state-out=cluster_dev.tfstate  "kubernetes_manifest.prometheus_operator_crds[\"thanosrulers\"]"   "kubernetes_manifest.prometheus_operator_crds[\"thanosrulers\"]"
terraform state mv  -state=../root_dev.tfstate -state-out=cluster_dev.tfstate  "kubernetes_manifest.ui_azure_external_secret"   "kubernetes_manifest.ui_azure_external_secret"
terraform state mv  -state=../root_dev.tfstate -state-out=cluster_dev.tfstate  "kubernetes_manifest.ui_sentry_dsn_external_secret"   "kubernetes_manifest.ui_sentry_dsn_external_secret"
terraform state mv  -state=../root_dev.tfstate -state-out=cluster_dev.tfstate  "kubernetes_namespace.airflow"  "kubernetes_namespace.airflow"
terraform state mv  -state=../root_dev.tfstate -state-out=cluster_dev.tfstate  "kubernetes_namespace.aws_observability"   "kubernetes_namespace.aws_observability"
terraform state mv  -state=../root_dev.tfstate -state-out=cluster_dev.tfstate  "kubernetes_namespace.cert_manager"   "kubernetes_namespace.cert_manager"
terraform state mv  -state=../root_dev.tfstate -state-out=cluster_dev.tfstate  "kubernetes_namespace.cluster_autoscaler"   "kubernetes_namespace.cluster_autoscaler"
terraform state mv  -state=../root_dev.tfstate -state-out=cluster_dev.tfstate  "kubernetes_namespace.external_dns"   "kubernetes_namespace.external_dns"
terraform state mv  -state=../root_dev.tfstate -state-out=cluster_dev.tfstate  "kubernetes_namespace.external_secrets"   "kubernetes_namespace.external_secrets"
terraform state mv  -state=../root_dev.tfstate -state-out=cluster_dev.tfstate  "kubernetes_namespace.ingress_nginx"   "kubernetes_namespace.ingress_nginx"
terraform state mv  -state=../root_dev.tfstate -state-out=cluster_dev.tfstate  "kubernetes_namespace.karpenter"   "kubernetes_namespace.karpenter"
terraform state mv  -state=../root_dev.tfstate -state-out=cluster_dev.tfstate  "kubernetes_namespace.keda"   "kubernetes_namespace.keda"
terraform state mv  -state=../root_dev.tfstate -state-out=cluster_dev.tfstate  "kubernetes_namespace.kyverno"   "kubernetes_namespace.kyverno"
terraform state mv  -state=../root_dev.tfstate -state-out=cluster_dev.tfstate  "kubernetes_namespace.mwaa"   "kubernetes_namespace.mwaa"
terraform state mv  -state=../root_dev.tfstate -state-out=cluster_dev.tfstate  "kubernetes_namespace.ui"   "kubernetes_namespace.ui"
terraform state mv  -state=../root_dev.tfstate -state-out=cluster_dev.tfstate  "kubernetes_role.airflow_execution"   "kubernetes_role.airflow_execution"
terraform state mv  -state=../root_dev.tfstate -state-out=cluster_dev.tfstate  "kubernetes_role.airflow_serviceaccount_management"   "kubernetes_role.airflow_serviceaccount_management"
terraform state mv  -state=../root_dev.tfstate -state-out=cluster_dev.tfstate  "kubernetes_role.mwaa_execution"   "kubernetes_role.mwaa_execution"
terraform state mv  -state=../root_dev.tfstate -state-out=cluster_dev.tfstate  "kubernetes_role.mwaa_external_secrets"   "kubernetes_role.mwaa_external_secrets"
terraform state mv  -state=../root_dev.tfstate -state-out=cluster_dev.tfstate  "kubernetes_role.mwaa_serviceaccount_management"   "kubernetes_role.mwaa_serviceaccount_management"
terraform state mv  -state=../root_dev.tfstate -state-out=cluster_dev.tfstate  "kubernetes_role_binding.airflow_execution"   "kubernetes_role_binding.airflow_execution"
terraform state mv  -state=../root_dev.tfstate -state-out=cluster_dev.tfstate  "kubernetes_role_binding.airflow_serviceaccount_management"   "kubernetes_role_binding.airflow_serviceaccount_management"
terraform state mv  -state=../root_dev.tfstate -state-out=cluster_dev.tfstate  "kubernetes_role_binding.mwaa_execution"   "kubernetes_role_binding.mwaa_execution"
terraform state mv  -state=../root_dev.tfstate -state-out=cluster_dev.tfstate  "kubernetes_role_binding.mwaa_external_secrets"   "kubernetes_role_binding.mwaa_external_secrets"
terraform state mv  -state=../root_dev.tfstate -state-out=cluster_dev.tfstate  "kubernetes_role_binding.mwaa_serviceaccount_management"   "kubernetes_role_binding.mwaa_serviceaccount_management"
terraform state mv  -state=../root_dev.tfstate -state-out=cluster_dev.tfstate  "kubernetes_secret.ui_app_secrets"   "kubernetes_secret.ui_app_secrets"
terraform state mv  -state=../root_dev.tfstate -state-out=cluster_dev.tfstate  "kubernetes_secret.ui_rds"   "kubernetes_secret.ui_rds"
terraform state mv  -state=../root_dev.tfstate -state-out=cluster_dev.tfstate  "kubernetes_service_account.mwaa_external_secrets_analytical_platform_data_production"   "kubernetes_service_account.mwaa_external_secrets_analytical_platform_data_production"
terraform state mv  -state=../root_dev.tfstate -state-out=cluster_dev.tfstate "kubernetes_storage_class.gp3" "kubernetes_storage_class.gp3"

# --- MODULE ---
terraform state mv  -state=../root_dev.tfstate -state-out=cluster_dev.tfstate "module.amazon_prometheus_proxy_iam_policy" "module.amazon_prometheus_proxy_iam_policy"
terraform state mv  -state=../root_dev.tfstate -state-out=cluster_dev.tfstate "module.amazon_prometheus_proxy_iam_role" "module.amazon_prometheus_proxy_iam_role"
terraform state mv  -state=../root_dev.tfstate -state-out=cluster_dev.tfstate "module.analytical_platform_ui_service_role" "module.analytical_platform_ui_service_role"
terraform state mv  -state=../root_dev.tfstate -state-out=cluster_dev.tfstate "module.aws_cloudwatch_metrics_pod_identity" "module.aws_cloudwatch_metrics_pod_identity"
terraform state mv  -state=../root_dev.tfstate -state-out=cluster_dev.tfstate "module.aws_cloudwatch_network_flow_monitor_iam_role" "module.aws_cloudwatch_network_flow_monitor_iam_role"
terraform state mv  -state=../root_dev.tfstate -state-out=cluster_dev.tfstate "module.aws_for_fluent_bit_iam_role" "module.aws_for_fluent_bit_iam_role"
terraform state mv  -state=../root_dev.tfstate -state-out=cluster_dev.tfstate "module.cert_manager_iam_role" "module.cert_manager_iam_role"
terraform state mv  -state=../root_dev.tfstate -state-out=cluster_dev.tfstate "module.cluster_autoscaler_iam_role" "module.cluster_autoscaler_iam_role"
terraform state mv  -state=../root_dev.tfstate -state-out=cluster_dev.tfstate "module.common_secrets_manager_kms" "module.common_secrets_manager_kms"
terraform state mv  -state=../root_dev.tfstate -state-out=cluster_dev.tfstate "module.ebs_csi_driver_iam_role" "module.ebs_csi_driver_iam_role"
terraform state mv  -state=../root_dev.tfstate -state-out=cluster_dev.tfstate "module.eks" "module.eks"
terraform state mv  -state=../root_dev.tfstate -state-out=cluster_dev.tfstate "module.eks_cluster_logs_kms" "module.eks_cluster_logs_kms"
terraform state mv  -state=../root_dev.tfstate -state-out=cluster_dev.tfstate "module.eks_ebs_kms" "module.eks_ebs_kms"
terraform state mv  -state=../root_dev.tfstate -state-out=cluster_dev.tfstate "module.eks_log_group" "module.eks_log_group"
terraform state mv  -state=../root_dev.tfstate -state-out=cluster_dev.tfstate "module.external_dns_iam_role" "module.external_dns_iam_role"
terraform state mv  -state=../root_dev.tfstate -state-out=cluster_dev.tfstate "module.external_secrets_iam_role" "module.external_secrets_iam_role"
terraform state mv  -state=../root_dev.tfstate -state-out=cluster_dev.tfstate "module.karpenter" "module.karpenter"
terraform state mv  -state=../root_dev.tfstate -state-out=cluster_dev.tfstate "module.karpenter_sqs_kms" "module.karpenter_sqs_kms"
terraform state mv  -state=../root_dev.tfstate -state-out=cluster_dev.tfstate "module.karpenter_sqs_kms_access_iam_policy" "module.karpenter_sqs_kms_access_iam_policy"
terraform state mv  -state=../root_dev.tfstate -state-out=cluster_dev.tfstate "module.managed_prometheus" "module.managed_prometheus"
terraform state mv  -state=../root_dev.tfstate -state-out=cluster_dev.tfstate "module.managed_prometheus_kms" "module.managed_prometheus_kms"
terraform state mv  -state=../root_dev.tfstate -state-out=cluster_dev.tfstate "module.managed_prometheus_kms_access_iam_policy" "module.managed_prometheus_kms_access_iam_policy"
terraform state mv  -state=../root_dev.tfstate -state-out=cluster_dev.tfstate "module.managed_prometheus_log_group" "module.managed_prometheus_log_group"
terraform state mv  -state=../root_dev.tfstate -state-out=cluster_dev.tfstate "module.managed_prometheus_logs_kms" "module.managed_prometheus_logs_kms"
terraform state mv  -state=../root_dev.tfstate -state-out=cluster_dev.tfstate "module.rds_security_group" "module.rds_security_group"
terraform state mv  -state=../root_dev.tfstate -state-out=cluster_dev.tfstate "module.ui_azure_client_secret" "module.ui_azure_client_secret"
terraform state mv  -state=../root_dev.tfstate -state-out=cluster_dev.tfstate "module.ui_rds" "module.ui_rds"
terraform state mv  -state=../root_dev.tfstate -state-out=cluster_dev.tfstate "module.ui_rds_kms" "module.ui_rds_kms"
terraform state mv  -state=../root_dev.tfstate -state-out=cluster_dev.tfstate "module.ui_sentry_dsn_secret" "module.ui_sentry_dsn_secret"
terraform state mv  -state=../root_dev.tfstate -state-out=cluster_dev.tfstate "module.vpc_cni_iam_role" "module.vpc_cni_iam_role"

# --- RANDOM ---
terraform state mv  -state=../root_dev.tfstate -state-out=cluster_dev.tfstate "random_password.ui_app_secrets" "random_password.ui_app_secrets"
terraform state mv  -state=../root_dev.tfstate -state-out=cluster_dev.tfstate "random_password.ui_rds" "random_password.ui_rds"
