FROM mcr.microsoft.com/devcontainers/base:ubuntu

COPY .devcontainer/features/src/base/src/usr/local/bin/devcontainer-utils /usr/local/bin/devcontainer-utils

RUN install --directory --owner=vscode --group=vscode /home/vscode/.devcontainer/feature-completion

RUN apt-get update \
    && apt-get install --yes \
      python3-pip \
    && pip3 install --no-cache-dir --upgrade pip
