apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: echo-route
  namespace: test-workload
spec:
  parentRefs:
    - name: shared-alb
      namespace: lbc-test
  hostnames:
    - "echo2.cp-0806-1543.development.container-platform.service.justice.gov.uk"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      filters:
        - type: ExtensionRef
          extensionRef:
            group: gateway.k8s.aws
            kind: ListenerRuleConfiguration
            name: echo-source-ip-allowlist
      backendRefs:
        - name: echo
          port: 80
