apiVersion: gateway.k8s.aws/v1beta1
kind: ListenerRuleConfiguration
metadata:
  name: echo-source-ip-allowlist
  namespace: test-workload
spec:
  conditions:
    - field: source-ip
      sourceIPConfig:
        values:
          - 83.100.215.187/32
