
variable "lambda_name" {}
variable "vpc_id" {}
variable "subnet_ids" {
  type = list(string)
}
variable "ftp_port" {}
variable "ftp_protocol" {}
variable "ftp_transfer_type" {}
variable "ftp_file_types" {}
variable "ftp_local_path" {}
variable "ftp_remote_path" {}
variable "ftp_require_ssl" {}
variable "ftp_insecure" {}
variable "ftp_ca_cert" {}
variable "ftp_cert" {}
variable "ftp_key" {}
variable "ftp_key_type" {}
variable "slack_webhook" {}
variable "skip_key_verification" {}
variable "ftp_file_remove" {}
variable "ftp_cron" {}
variable "ftp_bucket" {}
variable "secret_name" {}
variable "env" {}
variable "s3_bucket_ftp" {}
variable "s3_object_ftp_client" {}
variable "s3_object_ftp_clientlibs" {}
variable "secret_arn" {}
