---
name: cloud-platform-non-live-hijacked
on:
  push:
    branches:
      - feature-hijack-gh
    paths:
      - 'terraform/environments/cloud-platform-non-live/**'
      - '.github/workflows/cloud-platform-non-live-hijacked.yml'

permissions:
  id-token: write  # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

env:
  APPLICATION: "cloud-platform-non-live"
  ACCOUNT_NAME: "cloud-platform-non-live-development"

jobs:
    fetch-secrets:
      uses: ministryofjustice/modernisation-platform-github-actions/.github/workflows/aws-secrets-management.yml@5c713c93eea694829b1bd3f410d0b235053318ce # v4.0.0
      secrets:
        MODERNISATION_PLATFORM_ACCOUNT_NUMBER: ${{ secrets.MODERNISATION_PLATFORM_ACCOUNT_ID }}
        PASSPHRASE: ${{ secrets.PASSPHRASE }}

    terraform-actions:
      runs-on: ubuntu-latest
      needs: fetch-secrets
      outputs:
        plan_exitcode: "${{ steps.plan.outputs.exitcode }}"
      steps:
        - name: Debug
          run: |
            pwd
            echo "account_name=${{ env.ACCOUNT_NAME }}"

        - name: Checkout Repository
          uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
          with:
            ref: feature-hijack-gh

        - name: Decrypt Secrets
          uses: ministryofjustice/modernisation-platform-github-actions/decrypt-secrets@5c713c93eea694829b1bd3f410d0b235053318ce # v4.0.0
          with:
            environment_management: ${{ needs.fetch-secrets.outputs.environment_management }}
            github_ci_user_environments_repo_pat: ${{ needs.fetch-secrets.outputs.github_ci_user_environments_repo_pat }}
            PASSPHRASE: ${{ secrets.PASSPHRASE }}

        - name: Get AWS Account Number
          run: |
            ACCOUNT_NUMBER=$(jq -r -e --arg account_name "${ACCOUNT_NAME}" '.account_ids[$account_name]' <<< $ENVIRONMENT_MANAGEMENT)
            echo "::add-mask::$ACCOUNT_NUMBER"
            echo "ACCOUNT_NUMBER=${ACCOUNT_NUMBER}" >> $GITHUB_ENV

        - name: Get Backend AWS Account Number
          run: |
            BACKEND_NUMBER=$(jq -r -e '.modernisation_platform_account_id' <<< $ENVIRONMENT_MANAGEMENT)
            echo "::add-mask::$BACKEND_NUMBER"
            echo "BACKEND_NUMBER=${BACKEND_NUMBER}" >> $GITHUB_ENV

        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7  # v6.0.0
          with:
            role-to-assume: "arn:aws:iam::${{ env.ACCOUNT_NUMBER }}:role/github-actions"
            role-session-name: githubactionsrolesession
            aws-region: "eu-west-2"

        - name: Setup Terraform
          uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd  # v3.1.2
          with:
            terraform_version: "${{ inputs.terraform_version }}"
            terraform_wrapper: false

        #
        # Terraform Init
        #
        - name: Terraform Init
          working-directory: "terraform/environments/${{ env.APPLICATION }}/"
          run: |
            pwd
            ls -la
            terraform --version
            echo "terraform init"
            terraform init

        #
        # Terraform Workspace Select
        #
        - name: Terraform Workspace Select
          working-directory: "terraform/environments/${{ env.APPLICATION }}/"
          run: |
            terraform workspace select "${ACCOUNT_NAME}"

        - name: Terraform Plan
          working-directory: "terraform/environments/${{ env.APPLICATION }}/"
          run: |
            set -o pipefail
            tf_args="-out x.tfplan ${{ inputs.plan_apply_tfargs }}"
            echo "terraform workspace list"
            terraform workspace list
            echo "terraform plan ${tf_args}"
            terraform plan ${tf_args} | bash ${GITHUB_WORKSPACE}/scripts/redact-output.sh

        - name: Terraform Apply
          working-directory: "terraform/environments/${{ env.APPLICATION }}/"
          run: |
            set -o pipefail
            tf_args="${{ inputs.plan_apply_tfargs }} x.tfplan"
            echo "terraform apply ${tf_args}"
            terraform apply ${tf_args} | bash ${GITHUB_WORKSPACE}/scripts/redact-output.sh
