---
name: Code Quality

"on":
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, edited, reopened, synchronize]
  schedule:
    - cron: "0 7 * * 1-5"
  workflow_dispatch:

permissions: {}

jobs:
  code-quality:
    permissions:
      actions: read
      contents: write
      issues: write
      pull-requests: write
      security-events: write
    uses: ministryofjustice/modernisation-platform-github-actions/.github/workflows/reusable-code-quality.yml@51a39f5eba93a24bacfdb24b8fda4a244c266018 # v6.2.12
    with:
      validate_all_codebase: ${{ github.event_name == 'schedule' && 'true' || 'false' }}
      apply_fixes: ${{ github.event_name == 'schedule' }}
      disable_linters: ${{ github.event_name == 'pull_request' && 'REPOSITORY_GRYPE' || '' }}
      codeql_languages: '["actions","go","javascript-typescript","python"]'
      checkov_arguments: >-
        --skip-check CKV_GIT_1,CKV_AWS_126,CKV2_AWS_38,CKV2_AWS_39
      tflint_arguments: >-
        --disable-rule=terraform_unused_declarations
