---
name: Go tests
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # trigger every sunday at 10:00am
    - cron: '0 10 * * 0'
  workflow_dispatch:
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_IN_AUTOMATION: true
  # NUKE_SKIP_SANDBOX_ACCOUNTS is a comma-separated list of account names to be skipped from the
  # sandbox_accounts_test.go test. For example: "xhibit-portal-development,another-development,".
  # As can be observed in the example above, every account name needs a leading comma, hence the last comma in the list.
  NUKE_SKIP_SANDBOX_ACCOUNTS: xhibit-portal-development,
jobs:
  go-tests:
    name: Run Go Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Download Go Modules
        working-directory: scripts/tests/go-tests
        run: go mod download
      - name: Run Go Tests
        working-directory: scripts/tests/go-tests
        run: go test -v
