---
name: Go tests
on:
  pull_request:
    types: [ opened, edited, reopened, synchronize ]
  schedule:
    # * is a special character in YAML so you have to quote this string
    # trigger every sunday at 10:00am
    - cron: '0 10 * * 0'
  workflow_dispatch:
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_IN_AUTOMATION: true
  # NUKE_SKIP_SANDBOX_ACCOUNTS: bichard7-sandbox-shared, core-vpc-sandbox,
jobs:
  go-tests:
    name: Run Go Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Download Go Modules
        working-directory: scripts/tests/go-tests
        run: go mod download
      - name: Run Go Tests
        working-directory: scripts/tests/go-tests
        run: go test -v
