---
name: OpenID Connect Sprinkler
on:
  push
env:
  TF_IN_AUTOMATION: true
  BUCKET_NAME: "bastion-sprinkler-development-nicbpi"
  AWS_REGION: "eu-west-2"
# permission can be added at job level or workflow level
permissions:
  id-token: write
  contents: read    # This is required for actions/checkout
jobs:
  S3FileUpload:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ env.ACCOUNT_ID }}:role/MemberInfrastructureAccess
          role-session-name: samplerolesession
          aws-region: ${{ env.AWS_REGION }}
        env:
          ACCOUNT_ID: 348456244381 # sprinkler-development





      # Upload a file to AWS s3
      - name: Copy LICENSE to s3
        run: |
          aws s3 cp ./LICENSE s3://${{ env.BUCKET_NAME }}/
