---
name: plan

on:
  workflow_call:
    inputs:
      application:
        type: string
        required: true
      environment:
        type: string
        required: true
    secrets:
      modernisation_platform_environments:
        type: string
        required: true
      github_token:
        type: string
        required: true

env:
  GITHUB_TOKEN: ${{ secrets.github_token }}
  TF_VAR_BRANCH_NAME: ${{ github.event_name == 'pull_request' && 'main' || (github.head_ref || github.ref_name) }}
  TF_VAR_GH_ACTOR_NAME: ${{ github.actor }}
  AWS_REGION: "eu-west-2"
  ACCOUNT_NAME: "${{ input.application }}-${{ input.environment }}"
  APPLICATION: "${{ input.application }}"

jobs:

  plan:
    steps:
      - name: Checkout Repository
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c  # v3.3.0

      - name: Set Account Number
        run: echo "ACCOUNT_NUMBER=$(jq -r -e --arg account_name "${ACCOUNT_NAME}" '.account_ids[$account_name]' <<< ${{ secrets.modernisation_platform_environments }})" >> $GITHUB_ENV

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@67fbcbb121271f7775d2e7715933280b06314838  # v1.7.0
        with:
          role-to-assume: "arn:aws:iam::${{ env.ACCOUNT_NUMBER }}:role/github-actions"
          role-session-name: githubactionsrolesession
          aws-region: ${{ env.AWS_REGION }}

      - name: Load and Configure Terraform
        uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1  # v2.0.3
        with:
          terraform_version: "~1"
          terraform_wrapper: false

      - name: Terraform plan
        run: |
          terraform --version
          echo "Terraform plan - ${ACCOUNT_NAME}"
          bash scripts/terraform-init.sh terraform/environments/${APPLICATION}
          terraform -chdir="terraform/environments/$APPLICATION}" workspace select "${ACCOUNT_NAME}"
          bash scripts/terraform-plan.sh terraform/environments/${APPLICATION}
