---
name: sprinkler

env:
  BACKEND_ACCOUNT_ID: ${{ secrets.MODERNISATION_PLATFORM_ACCOUNT_ID }}

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/environments/sprinkler/**'
      - '.github/workflows/sprinkler.yml'

  pull_request:
    branches:
      - main
    types: [opened, edited, reopened, synchronize]
    paths:
      - 'terraform/environments/sprinkler/**'
      - '.github/workflows/sprinkler.yml'

  workflow_dispatch:
    inputs:
      action:
        description: 'Set either [deploy|destroy].'
        default: 'deploy'
        required: true
        type: string
        options:
          - deploy
          - destroy

permissions:
  id-token: write  # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:

  show-backend-id:
    runs-on: ubuntu-latest
    steps:
      - name: echo-id
        run: echo $BACKEND_ACCOUNT_ID

  strategy:
    uses: ./.github/workflows/reusable_terraform_strategy.yml
    if: inputs.action != 'destroy'
    with:
      application: "${{ github.workflow }}"

  terraform:
    needs: strategy
    if: inputs.action != 'destroy'
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.strategy.outputs.matrix) }}
    uses: ./.github/workflows/reusable_terraform_plan_apply.yml
    with:
      application: "${{ github.workflow }}"
      environment: "${{ matrix.target }}"
      action: "${{ matrix.action }}"
      init_plan_apply_tfargs: "$BACKEND_ACCOUNT_ID"
    secrets:
      modernisation_platform_environments: "${{ secrets.MODERNISATION_PLATFORM_ENVIRONMENTS }}"
      pipeline_github_token: "${{ secrets.MODERNISATION_PLATFORM_CI_USER_ENVIRONMENTS_REPO_PAT }}"

  destroy-development:
    if: inputs.action == 'destroy'
    uses: ./.github/workflows/reusable_terraform_plan_apply.yml
    with:
      application: "${{ github.workflow }}"
      environment: "development"
      action: "plan_apply"
      plan_apply_tfargs: "-destroy"
    secrets:
      modernisation_platform_environments: "${{ secrets.MODERNISATION_PLATFORM_ENVIRONMENTS }}"
      pipeline_github_token: "${{ secrets.MODERNISATION_PLATFORM_CI_USER_ENVIRONMENTS_REPO_PAT }}"
