---
name: sprinkler
on:
 push:
   branches:
     - main
   paths:
     - 'terraform/environments/sprinkler/**'
     - '.github/workflows/sprinkler.yml'
 pull_request:
   branches:
     - main
   types: [opened, edited, reopened, synchronize]
   paths:
     - 'terraform/environments/sprinkler/**'
     - '.github/workflows/sprinkler.yml'
 workflow_dispatch:
env:
 AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
 AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
 TF_IN_AUTOMATION: true
defaults:
 run:
   shell: bash

jobs:

 # These jobs run when creating a pull request
 plan-development:
   name: Plan Development - sprinkler
   runs-on: ubuntu-latest
   if: github.ref != 'refs/heads/main' || github.event_name == 'workflow_dispatch'
   steps:
     - name: Checkout Repository
       uses: actions/checkout@v3.0.2
     - name: Load and Configure Terraform
       uses: hashicorp/setup-terraform@v2.0.0
       with:
         terraform_version: 1.0.1
         terraform_wrapper: false
     - name: Terraform plan - development
       run: |
         echo "Terraform plan - ${TF_ENV}"
         bash scripts/terraform-init.sh terraform/environments/sprinkler
         terraform -chdir="terraform/environments/sprinkler" workspace select "sprinkler-${TF_ENV}"
         bash scripts/terraform-plan.sh terraform/environments/sprinkler
       env:
         TF_ENV: development

 deploy-development:
   name: Deploy Development - sprinkler
   runs-on: ubuntu-latest
   if: github.ref != 'refs/heads/main' || github.event_name == 'workflow_dispatch'
   environment:
     name: sprinkler-development
   steps:
     - name: Checkout Repository
       uses: actions/checkout@v3.0.2
     - name: Load and Configure Terraform
       uses: hashicorp/setup-terraform@v2.0.0
       with:
         terraform_version: 1.0.1
         terraform_wrapper: false
     - name: Terraform apply - development
       run: |
         echo "Terraform apply - ${TF_ENV}"
         bash scripts/terraform-init.sh terraform/environments/sprinkler
         terraform -chdir="terraform/environments/sprinkler" workspace select "sprinkler-${TF_ENV}"
         bash scripts/terraform-apply.sh terraform/environments/sprinkler
       env:
         TF_ENV: development
