name: nomis
on:
  workflow_dispatch:
env:
  AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_IN_AUTOMATION: true
defaults:
  run:
    shell: bash

jobs:
  plan-test:
    name: Upgrade Provider
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.3.4
      - name: Load and Configure Terraform
        uses: hashicorp/setup-terraform@v1.3.2
        with:
          terraform_version: 1.1.7
          terraform_wrapper: false
      - name: Terraform plan - test
        run: |
          echo "Terraform plan - ${TF_ENV}"
          bash scripts/terraform-init.sh terraform/environments/nomis
          terraform -chdir="terraform/environments/nomis" workspace select "nomis-${TF_ENV}"
          terraform state replace-provider registry.terraform.io/hashicorp/github registry.terraform.io/integrations/github -auto-approve -chdir="terraform/environments/nomis"
        env:
          TF_ENV: test
