---
name: threat-and-vulnerability-mgmt
on:
  push:
    branches: 
      - main
    paths:
      - 'terraform/environments/threat-and-vulnerability-mgmt/**'
      - '.github/workflows/threat-and-vulnerability-mgmt.yml'
  pull_request:
    branches:
      - main
    types: [opened, edited, reopened, synchronize]
    paths:
      - 'terraform/environments/threat-and-vulnerability-mgmt/**'
      - '.github/workflows/threat-and-vulnerability-mgmt.yml'
  workflow_dispatch:
env:
  AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_IN_AUTOMATION: true
defaults:
  run:
    shell: bash

jobs:
  
  # These jobs run when creating a pull request
  plan-development:
    name: Plan Development - threat-and-vulnerability-mgmt
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3.1.0
      - name: Load and Configure Terraform
        uses: hashicorp/setup-terraform@v2.0.0
        with:
          terraform_version: "~1"
          terraform_wrapper: false
      - name: Terraform plan - development
        run: |
          terraform --version
          echo "Terraform plan - ${TF_ENV}"
          bash scripts/terraform-init.sh terraform/environments/threat-and-vulnerability-mgmt
          terraform -chdir="terraform/environments/threat-and-vulnerability-mgmt" workspace select "threat-and-vulnerability-mgmt-${TF_ENV}"
          bash scripts/terraform-plan.sh terraform/environments/threat-and-vulnerability-mgmt
        env:
          TF_ENV: development

  deploy-development:
    name: Deploy Development - threat-and-vulnerability-mgmt
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main' || github.event_name == 'workflow_dispatch'
    environment:
      name: threat-and-vulnerability-mgmt-development
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3.1.0
      - name: Load and Configure Terraform
        uses: hashicorp/setup-terraform@v2.0.0
        with:
          terraform_version: "~1"
          terraform_wrapper: false
      - name: Terraform apply - development
        run: |
          terraform --version
          echo "Terraform apply - ${TF_ENV}"
          bash scripts/terraform-init.sh terraform/environments/threat-and-vulnerability-mgmt
          terraform -chdir="terraform/environments/threat-and-vulnerability-mgmt" workspace select "threat-and-vulnerability-mgmt-${TF_ENV}"
          bash scripts/terraform-apply.sh terraform/environments/threat-and-vulnerability-mgmt
        env:
          TF_ENV: development
  
  plan-production:
    name: Plan Production - threat-and-vulnerability-mgmt
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3.1.0
      - name: Load and Configure Terraform
        uses: hashicorp/setup-terraform@v2.0.0
        with:
          terraform_version: "~1"
          terraform_wrapper: false
      - name: Terraform plan - production
        run: |
          terraform --version
          echo "Terraform plan - ${TF_ENV}"
          bash scripts/terraform-init.sh terraform/environments/threat-and-vulnerability-mgmt
          terraform -chdir="terraform/environments/threat-and-vulnerability-mgmt" workspace select "threat-and-vulnerability-mgmt-${TF_ENV}"
          bash scripts/terraform-plan.sh terraform/environments/threat-and-vulnerability-mgmt
        env:
          TF_ENV: production

  deploy-production:
    name: Deploy Production - threat-and-vulnerability-mgmt
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment:
      name: threat-and-vulnerability-mgmt-production
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3.1.0
      - name: Load and Configure Terraform
        uses: hashicorp/setup-terraform@v2.0.0
        with:
          terraform_version: "~1"
          terraform_wrapper: false
      - name: Terraform apply - production
        run: |
          terraform --version
          echo "Terraform apply - ${TF_ENV}"
          bash scripts/terraform-init.sh terraform/environments/threat-and-vulnerability-mgmt
          terraform -chdir="terraform/environments/threat-and-vulnerability-mgmt" workspace select "threat-and-vulnerability-mgmt-${TF_ENV}"
          bash scripts/terraform-apply.sh terraform/environments/threat-and-vulnerability-mgmt
        env:
          TF_ENV: production
